// Code generated by kms-config-gen-ts; DO NOT EDIT.

import { isDeepStrictEqual } from "node:util";

import { Secret } from "../../../src/index.js";
import type { ReleaseSnapshot } from "../../../src/index.js";
import {
  CandidateError,
  cloneConfig,
  codecs,
  decodeGroup,
  encodeGroup,
  field,
  group,
  immutableSnapshot,
  ReleaseIdentity,
  rejectDecode,
  startManagedConfig,
} from "../../../src/configstore/index.js";
import type {
  ConfigSnapshot,
  ContractEntry,
  FieldDifference,
  GroupCodec,
  ManagedConfigManager,
  ManagedConfigOptions,
  ManagedPreparedCandidate,
  ManagedReleaseClient,
  ValueCodec,
} from "../../../src/configstore/index.js";
import type { Config } from "./config.js";

export const schemaSHA256 = "573d6f4f2e4606fd332ff8d431a568a88f9c4dee1d79da14b0dbf82abae47cd9";

export const generatedContract = Object.freeze([
  Object.freeze({ alias: "database", kind: "parameter", contentType: "json" }),
  Object.freeze({ alias: "runtime", kind: "parameter", contentType: "json" }),
  Object.freeze({ alias: "database_password", kind: "secret" }),
]) satisfies readonly ContractEntry[];

type Group0 = Pick<Config, "endpoint" | "limit">;
const valueCodec0_0: ValueCodec<Group0["endpoint"]> = codecs.object<Group0["endpoint"]>([field<Group0["endpoint"], "host">("host", "host", codecs.string), field<Group0["endpoint"], "ports">("ports", "ports", codecs.array(codecs.int({ bits: 16, unsigned: true })))]);
const valueCodec0_1: ValueCodec<Group0["limit"]> = codecs.int({ bits: 32, unsigned: false });
const groupCodec0: GroupCodec<Group0> = group<Group0>([
  field<Group0, "endpoint">("endpoint", "endpoint", valueCodec0_0),
  field<Group0, "limit">("limit", "limit", valueCodec0_1),
]);

type Group1 = Pick<Config, "enabled" | "epoch" | "labels" | "payload">;
const valueCodec1_0: ValueCodec<Group1["enabled"]> = codecs.boolean;
const valueCodec1_1: ValueCodec<Group1["epoch"]> = codecs.bigint({ bits: 64, unsigned: true });
const valueCodec1_2: ValueCodec<Group1["labels"]> = codecs.record(codecs.string);
const valueCodec1_3: ValueCodec<Group1["payload"]> = codecs.bytes;
const groupCodec1: GroupCodec<Group1> = group<Group1>([
  field<Group1, "enabled">("enabled", "enabled", valueCodec1_0),
  field<Group1, "epoch">("epoch", "epoch", valueCodec1_1),
  field<Group1, "labels">("labels", "labels", valueCodec1_2),
  field<Group1, "payload">("payload", "payload", valueCodec1_3),
]);

export const groupCodecs = Object.freeze({
  "database": groupCodec0,
  "runtime": groupCodec1,
});

export function encodeParameterGroups(config: Config): Readonly<Record<string, string>> {
  const source = cloneConfig(config);
  return Object.freeze({
    "database": encodeGroup(source, groupCodec0),
    "runtime": encodeGroup(source, groupCodec1),
  });
}

export class DatabaseHealthView {
  readonly #snapshot: ConfigSnapshot<Config>;

  constructor(snapshot: ConfigSnapshot<Config>) {
    this.#snapshot = snapshot;
    Object.freeze(this);
  }

  get ["endpoint"](): Config["endpoint"] {
    return this.#snapshot.get("endpoint");
  }

  get ["limit"](): Config["limit"] {
    return this.#snapshot.get("limit");
  }
}

export class WorkerView {
  readonly #snapshot: ConfigSnapshot<Config>;

  constructor(snapshot: ConfigSnapshot<Config>) {
    this.#snapshot = snapshot;
    Object.freeze(this);
  }

  get ["limit"](): Config["limit"] {
    return this.#snapshot.get("limit");
  }

  get ["password"](): Config["password"] {
    return this.#snapshot.get("password");
  }

  get ["enabled"](): Config["enabled"] {
    return this.#snapshot.get("enabled");
  }

  get ["epoch"](): Config["epoch"] {
    return this.#snapshot.get("epoch");
  }

  get ["labels"](): Config["labels"] {
    return this.#snapshot.get("labels");
  }

  get ["payload"](): Config["payload"] {
    return this.#snapshot.get("payload");
  }
}

export class Snapshot {
  readonly #snapshot: ConfigSnapshot<Config>;

  constructor(snapshot: ConfigSnapshot<Config>) {
    this.#snapshot = snapshot;
    Object.freeze(this);
  }

  get release(): ReleaseIdentity {
    return this.#snapshot.release;
  }

  config(): Config {
    return this.#snapshot.config();
  }

  databaseHealth(): DatabaseHealthView {
    return new DatabaseHealthView(this.#snapshot);
  }

  worker(): WorkerView {
    return new WorkerView(this.#snapshot);
  }
}

export type ValidateConfig = (config: Config) => void | Promise<void>;
export type StartOptions = Omit<ManagedConfigOptions, "contract">;

export class Store {
  readonly #defaults: ConfigSnapshot<Config>;
  readonly #validate: ValidateConfig;
  #active: ConfigSnapshot<Config> | undefined;
  #started = false;

  constructor(defaults: Config, validate: ValidateConfig) {
    if (typeof validate !== "function") throw new TypeError("generated config store: validate callback is required");
    const copiedDefaults = writableClone(defaults);
    assertZeroSecret(copiedDefaults["password"], "database_password");
    this.#defaults = immutableSnapshot(copiedDefaults);
    this.#validate = validate;
  }

  async start(
    client: ManagedReleaseClient,
    options: StartOptions,
    signal?: AbortSignal,
  ): Promise<ManagedConfigManager> {
    if (this.#started) throw new Error("generated config store: Store.start may only be called once");
    this.#started = true;
    return startManagedConfig(
      client,
      { ...options, contract: generatedContract },
      (snapshot, candidateSignal) => this.#prepare(snapshot, candidateSignal),
      signal,
    );
  }

  current(): Snapshot {
    const active = this.#active;
    if (!active) throw new Error("generated config store: configuration is not initialized");
    return new Snapshot(active);
  }

  async #prepare(snapshot: ReleaseSnapshot, signal: AbortSignal): Promise<ManagedPreparedCandidate> {
    throwIfAborted(signal);
    const candidate = writableClone(this.#defaults.config());
    const parameter0 = snapshot.parameter("database");
    if (!parameter0) throw contractMismatch();
    let decoded0: Group0;
    try {
      decoded0 = decodeGroup(parameter0.value(), groupCodec0);
    } catch (cause) {
      throw rejectDecode("database", cause);
    }
    setProperty(candidate, "endpoint", decoded0["endpoint"]);
    setProperty(candidate, "limit", decoded0["limit"]);
    const parameter1 = snapshot.parameter("runtime");
    if (!parameter1) throw contractMismatch();
    let decoded1: Group1;
    try {
      decoded1 = decodeGroup(parameter1.value(), groupCodec1);
    } catch (cause) {
      throw rejectDecode("runtime", cause);
    }
    setProperty(candidate, "enabled", decoded1["enabled"]);
    setProperty(candidate, "epoch", decoded1["epoch"]);
    setProperty(candidate, "labels", decoded1["labels"]);
    setProperty(candidate, "payload", decoded1["payload"]);
    const secret0 = snapshot.secret("database_password");
    if (!secret0) throw contractMismatch();
    const secretValue0 = new Secret(secret0.bytes(), {
      path: secret0.entry.path,
      version: secret0.entry.version,
      contentType: secret0.entry.contentType,
    });
    setProperty(candidate, "password", secretValue0);
    throwIfAborted(signal);
    const effectiveDefaults = writableClone(this.#defaults.config());
    setProperty(effectiveDefaults, "password", secretValue0.clone());
    try {
      const validationDefaults = writableClone(effectiveDefaults);
      await this.#validate(validationDefaults);
      throwIfAborted(signal);
      const validationCandidate = writableClone(candidate);
      await this.#validate(validationCandidate);
    } catch (cause) {
      if (signal.aborted) throw abortReason(signal);
      throw new CandidateError("config_validation_failed", cause);
    }
    throwIfAborted(signal);
    const defaultDifferences: FieldDifference[] = [];
    appendDifference(defaultDifferences, "database.endpoint", valueCodec0_0, effectiveDefaults["endpoint"], candidate["endpoint"]);
    appendDifference(defaultDifferences, "database.limit", valueCodec0_1, effectiveDefaults["limit"], candidate["limit"]);
    appendDifference(defaultDifferences, "runtime.enabled", valueCodec1_0, effectiveDefaults["enabled"], candidate["enabled"]);
    appendDifference(defaultDifferences, "runtime.epoch", valueCodec1_1, effectiveDefaults["epoch"], candidate["epoch"]);
    appendDifference(defaultDifferences, "runtime.labels", valueCodec1_2, effectiveDefaults["labels"], candidate["labels"]);
    appendDifference(defaultDifferences, "runtime.payload", valueCodec1_3, effectiveDefaults["payload"], candidate["payload"]);
    const restartRequiredFields: string[] = [];
    const active = this.#active;
    if (active) {
      appendRestart(restartRequiredFields, "database.endpoint", valueCodec0_0, active.get("endpoint"), candidate["endpoint"]);
      if (!sameSecretIdentity(active.get("password"), candidate["password"])) restartRequiredFields.push("database_password");
    }
    const prepared = immutableSnapshot(writableClone(candidate), ReleaseIdentity.from(snapshot));
    return {
      defaultDifferences,
      restartRequiredFields,
      publish: () => {
        this.#active = prepared;
      },
      abort: () => undefined,
    };
  }
}

function writableClone(value: Config): Config {
  const source = cloneConfig(value);
  const target = Object.create(Object.getPrototypeOf(source)) as object;
  for (const key of Reflect.ownKeys(source)) {
    const descriptor = Object.getOwnPropertyDescriptor(source, key);
    if (!descriptor || !("value" in descriptor)) {
      throw new TypeError("generated config store: accessor properties are not supported");
    }
    Object.defineProperty(target, key, { ...descriptor, writable: true, configurable: true });
  }
  return target as Config;
}

function setProperty<T extends object, K extends keyof T>(target: T, key: K, value: T[K]): void {
  const current = Object.getOwnPropertyDescriptor(target, key);
  Object.defineProperty(target, key, {
    value: cloneConfig(value),
    enumerable: current?.enumerable ?? true,
    writable: true,
    configurable: true,
  });
}

function appendDifference<T>(
  result: FieldDifference[],
  path: string,
  codec: ValueCodec<T>,
  expected: T,
  actual: T,
): void {
  if (!sameEncoded(codec, expected, actual)) result.push({ path, expected, actual });
}

function appendRestart<T>(result: string[], path: string, codec: ValueCodec<T>, active: T, candidate: T): void {
  if (!sameEncoded(codec, active, candidate)) result.push(path);
}

function sameEncoded<T>(codec: ValueCodec<T>, left: T, right: T): boolean {
  try {
    return isDeepStrictEqual(codec.encodeNode(left, "$"), codec.encodeNode(right, "$"));
  } catch (cause) {
    throw new CandidateError("config_validation_failed", cause);
  }
}

function sameSecretIdentity(left: unknown, right: unknown): boolean {
  return (
    left instanceof Secret &&
    right instanceof Secret &&
    left.path === right.path &&
    left.version === right.version
  );
}

function assertZeroSecret(value: unknown, alias: string): void {
  if (
    !(value instanceof Secret) ||
    !value.isEmpty ||
    value.path !== "" ||
    value.version !== 0n ||
    value.contentType !== ""
  ) {
    throw new TypeError("generated config store: secret default " + alias + " must be the zero Secret");
  }
}

function contractMismatch(): CandidateError {
  return new CandidateError(
    "config_contract_mismatch",
    new Error("generated config store: resolved release does not match contract"),
  );
}

function throwIfAborted(signal: AbortSignal): void {
  if (signal.aborted) throw abortReason(signal);
}

function abortReason(signal: AbortSignal): unknown {
  return signal.reason ?? new DOMException("Aborted", "AbortError");
}
