// Code generated by kms-config-gen-ts; DO NOT EDIT.

import { isDeepStrictEqual } from "node:util";

import type { ReleaseSnapshot } from "../../../src/index.js";
import {
  CandidateError,
  cloneConfig,
  encodeDefaultsArtifact as encodeDefaultsArtifactWire,
  immutableSnapshot,
  ReleaseIdentity,
  startManagedConfig,
  verifyDefaults,
  codecs,
  decodeGroup,
  encodeGroup,
  field,
  group,
  rejectDecode,
} from "../../../src/configstore/index.js";
import type {
  ConfigSnapshot,
  ContractEntry,
  FieldChange,
  FieldDifference,
  ManagedConfigManager,
  ManagedConfigOptions,
  ManagedPreparedCandidate,
  ManagedReleaseClient,
  VerifyClient,
  VerifyOptions,
  VerifyResult,
  GroupCodec,
  ValueCodec,
} from "../../../src/configstore/index.js";
import type { GroupsOnly as RootConfig } from "./config.js";

export const schemaSHA256 = "6a642a8a90dbaf7fb7174c55cebe715acd1a28271e43b612f57622294b34462e";

export const generatedContract = Object.freeze([
  Object.freeze({ alias: "application", kind: "parameter", contentType: "json" }),
]) satisfies readonly ContractEntry[];

assertRootCoverage<RootConfig, "name">();

type Group0 = Pick<RootConfig, "name">;
const valueCodec0_0: ValueCodec<Group0["name"]> = codecs.string;
const groupCodec0: GroupCodec<Group0> = exactObject<Group0, "name">(group<Group0>([
  field<Group0, "name">("name", "name", valueCodec0_0),
]));

export const groupCodecs = Object.freeze({
  "application": groupCodec0,
});

export function encodeParameterGroups(config: RootConfig): Readonly<Record<string, string>> {
  const source = cloneConfig(config);
  return Object.freeze({
    "application": encodeGroup(source, groupCodec0),
  });
}

export function encodeDefaultsArtifact(profile: string, config: RootConfig): string {
  return encodeDefaultsArtifactWire({
    profile,
    schemaSHA256,
    contract: generatedContract,
    parameters: encodeParameterGroups(config),
  });
}

/**
 * Ask KMS which parameter groups of config differ from the active release of
 * options.namespace. Only canonical content hashes travel over the wire; no
 * value is ever sent or returned.
 */
export function verifyReleaseDefaults(
  client: VerifyClient,
  config: RootConfig,
  options: VerifyOptions,
): Promise<VerifyResult> {
  return verifyDefaults(
    client,
    { schemaSha256: schemaSHA256, contract: generatedContract, groups: encodeParameterGroups(config) },
    options,
  );
}

export class WorkerView {
  readonly #snapshot: ConfigSnapshot<RootConfig>;

  constructor(snapshot: ConfigSnapshot<RootConfig>) {
    this.#snapshot = snapshot;
    Object.freeze(this);
  }

  get ["name"](): RootConfig["name"] {
    return this.#snapshot.get("name");
  }
}

export class Snapshot {
  readonly #snapshot: ConfigSnapshot<RootConfig>;

  constructor(snapshot: ConfigSnapshot<RootConfig>) {
    this.#snapshot = snapshot;
    Object.freeze(this);
  }

  get release(): ReleaseIdentity {
    return this.#snapshot.release;
  }

  config(): RootConfig {
    return this.#snapshot.config();
  }

  worker(): WorkerView {
    return new WorkerView(this.#snapshot);
  }
}

export type ValidateConfig = (config: RootConfig) => void | Promise<void>;
export type StartOptions = Omit<ManagedConfigOptions, "contract">;

export class Store {
  readonly #defaults: ConfigSnapshot<RootConfig>;
  readonly #validate: ValidateConfig;
  #active: ConfigSnapshot<RootConfig> | undefined;
  #started = false;

  constructor(defaults: RootConfig, validate: ValidateConfig) {
    if (typeof validate !== "function") throw new TypeError("generated config store: validate callback is required");
    const copiedDefaults = writableClone(defaults);
    this.#defaults = immutableSnapshot(copiedDefaults);
    this.#validate = validate;
  }

  async start(
    client: ManagedReleaseClient,
    options: StartOptions,
    signal?: AbortSignal,
  ): Promise<ManagedConfigManager> {
    if (this.#started) throw new Error("generated config store: Store.start may only be called once");
    this.#started = true;
    return startManagedConfig(
      client,
      { ...options, contract: generatedContract },
      (snapshot, candidateSignal) => this.#prepare(snapshot, candidateSignal),
      signal,
    );
  }

  current(): Snapshot {
    const active = this.#active;
    if (!active) throw new Error("generated config store: configuration is not initialized");
    return new Snapshot(active);
  }

  async #prepare(snapshot: ReleaseSnapshot, signal: AbortSignal): Promise<ManagedPreparedCandidate> {
    throwIfAborted(signal);
    const candidate = writableClone(this.#defaults.config());
    const parameter0 = snapshot.parameter("application");
    if (!parameter0 || parameter0.entry.alias !== "application" || parameter0.entry.kind !== "parameter" || parameter0.entry.contentType !== "json") throw contractMismatch();
    let decoded0: Group0;
    try {
      decoded0 = decodeGroup(parameter0.value(), groupCodec0);
    } catch (cause) {
      throw rejectDecode("application", cause);
    }
    setProperty(candidate, "name", decoded0["name"]);
    throwIfAborted(signal);
    const effectiveDefaults = writableClone(this.#defaults.config());
    let validatedCandidate: RootConfig;
    let validatedDefaults: RootConfig;
    try {
      await this.#validate(candidate);
      throwIfAborted(signal);
      await this.#validate(effectiveDefaults);
      throwIfAborted(signal);
      validatedCandidate = writableClone(candidate);
      validatedDefaults = writableClone(effectiveDefaults);
    } catch (cause) {
      if (signal.aborted) throw abortReason(signal);
      throw new CandidateError("config_validation_failed", cause);
    }
    throwIfAborted(signal);
    const defaultDifferences: FieldDifference[] = [];
    appendDifference(defaultDifferences, "application.name", valueCodec0_0, validatedDefaults["name"], validatedCandidate["name"]);
    const restartRequiredFields: string[] = [];
    const active = this.#active;
    if (active) {
    }
    restartRequiredFields.sort();
    // Changed fields versus the previously applied generation feed onApplied. Secrets are path-only.
    const changed: FieldChange[] = [];
    if (active) {
      appendChange(changed, "application.name", valueCodec0_0, active.get("name"), validatedCandidate["name"]);
    }
    // Group documents feed observability only; an encoding failure must never reject a candidate.
    let groups: Readonly<Record<string, string>>;
    try {
      groups = encodeParameterGroups(validatedCandidate);
    } catch {
      groups = {};
    }
    const prepared = immutableSnapshot(validatedCandidate, ReleaseIdentity.from(snapshot));
    return {
      defaultDifferences,
      restartRequiredFields,
      changed,
      groups,
      publish: () => {
        this.#active = prepared;
      },
      abort: () => undefined,
    };
  }
}

function assertRootCoverage<T extends object, K extends PropertyKey>(
  ...missing: IsUnion<T> extends true ? [never] : [Exclude<keyof T, K>, Exclude<K, keyof T>] extends [never, never] ? [] : [never]
): void {
  void missing;
}

function exactObject<T extends object, K extends keyof T & string>(
  codec: IsUnion<T> extends true ? never : Exclude<keyof T, K> extends never ? GroupCodec<T> : never,
): GroupCodec<T> {
  return codec;
}

type IsUnion<T, Whole = T> = T extends unknown
  ? [Whole] extends [T]
    ? false
    : true
  : never;

function writableClone(value: RootConfig): RootConfig {
  const source = cloneConfig(value);
  const target = Object.create(Object.getPrototypeOf(source)) as object;
  for (const key of Reflect.ownKeys(source)) {
    const descriptor = Object.getOwnPropertyDescriptor(source, key);
    if (!descriptor || !("value" in descriptor)) {
      throw new TypeError("generated config store: accessor properties are not supported");
    }
    Object.defineProperty(target, key, { ...descriptor, writable: true, configurable: true });
  }
  return target as RootConfig;
}

function setProperty<T extends object, K extends keyof T>(target: T, key: K, value: T[K]): void {
  const current = Object.getOwnPropertyDescriptor(target, key);
  Object.defineProperty(target, key, {
    value: cloneConfig(value),
    enumerable: current?.enumerable ?? true,
    writable: true,
    configurable: true,
  });
}

type EncodedNode = ReturnType<ValueCodec<unknown>["encodeNode"]>;

function appendDifference<T>(
  result: FieldDifference[],
  path: string,
  codec: ValueCodec<T>,
  expected: T,
  actual: T,
): void {
  if (!sameEncoded(codec, expected, actual)) result.push({ path, expected, actual });
}

function appendChange<T>(
  result: FieldChange[],
  path: string,
  codec: ValueCodec<T>,
  previous: T,
  current: T,
): void {
  if (!sameEncoded(codec, previous, current)) result.push({ path, previous, current });
}

function sameEncoded<T>(codec: ValueCodec<T>, left: T, right: T): boolean {
  try {
    return isDeepStrictEqual(canonicalNode(codec.encodeNode(left, "$")), canonicalNode(codec.encodeNode(right, "$")));
  } catch (cause) {
    throw new CandidateError("config_validation_failed", cause);
  }
}

function canonicalNode(node: EncodedNode): EncodedNode {
  if (node.kind === "array") {
    return { kind: "array", elements: node.elements.map(canonicalNode) };
  }
  if (node.kind === "object") {
    return {
      kind: "object",
      properties: node.properties
        .map(({ name, value }) => ({ name, value: canonicalNode(value) }))
        .sort((left, right) => left.name < right.name ? -1 : left.name > right.name ? 1 : 0),
    };
  }
  return node;
}

function contractMismatch(): CandidateError {
  return new CandidateError(
    "config_contract_mismatch",
    new Error("generated config store: resolved release does not match contract"),
  );
}

function throwIfAborted(signal: AbortSignal): void {
  if (signal.aborted) throw abortReason(signal);
}

function abortReason(signal: AbortSignal): unknown {
  return signal.reason ?? new DOMException("Aborted", "AbortError");
}
