// Code generated by kms-config-gen-ts; DO NOT EDIT.

import { Secret } from "../../../src/index.js";
import type { ReleaseSnapshot } from "../../../src/index.js";
import {
  CandidateError,
  cloneConfig,
  encodeDefaultsArtifact as encodeDefaultsArtifactWire,
  immutableSnapshot,
  ReleaseIdentity,
  startManagedConfig,
  verifyDefaults,
} from "../../../src/configstore/index.js";
import type {
  ConfigSnapshot,
  ContractEntry,
  FieldChange,
  FieldDifference,
  ManagedConfigManager,
  ManagedConfigOptions,
  ManagedPreparedCandidate,
  ManagedReleaseClient,
  VerifyClient,
  VerifyOptions,
  VerifyResult,
} from "../../../src/configstore/index.js";
import type { SecretsOnly as RootConfig } from "./config.js";

export const schemaSHA256 = "93abdf79e846e56f4c9946edc3f5960292701a28ab5619219747888e7022626c";

export const generatedContract = Object.freeze([
  Object.freeze({ alias: "worker_token", kind: "secret" }),
]) satisfies readonly ContractEntry[];

assertRootCoverage<RootConfig, "token">();

export const groupCodecs = Object.freeze({
});

export function encodeParameterGroups(config: RootConfig): Readonly<Record<string, string>> {
  void config;
  return Object.freeze({
  });
}

export function encodeDefaultsArtifact(profile: string, config: RootConfig): string {
  return encodeDefaultsArtifactWire({
    profile,
    schemaSHA256,
    contract: generatedContract,
    parameters: encodeParameterGroups(config),
  });
}

/**
 * Ask KMS which parameter groups of config differ from the active release of
 * options.namespace. Only canonical content hashes travel over the wire; no
 * value is ever sent or returned.
 */
export function verifyReleaseDefaults(
  client: VerifyClient,
  config: RootConfig,
  options: VerifyOptions,
): Promise<VerifyResult> {
  return verifyDefaults(
    client,
    { schemaSha256: schemaSHA256, contract: generatedContract, groups: encodeParameterGroups(config) },
    options,
  );
}

export class WorkerView {
  readonly #snapshot: ConfigSnapshot<RootConfig>;

  constructor(snapshot: ConfigSnapshot<RootConfig>) {
    this.#snapshot = snapshot;
    Object.freeze(this);
  }

  get ["token"](): RootConfig["token"] {
    return this.#snapshot.get("token");
  }
}

export class Snapshot {
  readonly #snapshot: ConfigSnapshot<RootConfig>;

  constructor(snapshot: ConfigSnapshot<RootConfig>) {
    this.#snapshot = snapshot;
    Object.freeze(this);
  }

  get release(): ReleaseIdentity {
    return this.#snapshot.release;
  }

  config(): RootConfig {
    return this.#snapshot.config();
  }

  worker(): WorkerView {
    return new WorkerView(this.#snapshot);
  }
}

export type ValidateConfig = (config: RootConfig) => void | Promise<void>;
export type StartOptions = Omit<ManagedConfigOptions, "contract" | "bindingKeys">;

export class Store {
  readonly #defaults: ConfigSnapshot<RootConfig>;
  readonly #bindingKeys: Readonly<Record<string, string>>;
  readonly #validate: ValidateConfig;
  #active: ConfigSnapshot<RootConfig> | undefined;
  #started = false;

  constructor(defaults: RootConfig, validate: ValidateConfig) {
    if (typeof validate !== "function") throw new TypeError("generated config store: validate callback is required");
    const copiedDefaults = writableClone(defaults);
    const bindingKeys = Object.create(null) as Record<string, string>;
    assertZeroSecret(copiedDefaults["token"], "worker_token");
    if (copiedDefaults["token"].bindKey.length > 0) {
      bindingKeys["worker_token"] = copiedDefaults["token"].bindKey;
    }
    setProperty(copiedDefaults, "token", new Secret());
    this.#bindingKeys = Object.freeze(bindingKeys);
    this.#defaults = immutableSnapshot(copiedDefaults);
    this.#validate = validate;
  }

  async start(
    client: ManagedReleaseClient,
    options: StartOptions,
    signal?: AbortSignal,
  ): Promise<ManagedConfigManager> {
    if (this.#started) throw new Error("generated config store: Store.start may only be called once");
    this.#started = true;
    return startManagedConfig(
      client,
      { ...options, bindingKeys: this.#bindingKeys, contract: generatedContract },
      (snapshot, candidateSignal) => this.#prepare(snapshot, candidateSignal),
      signal,
    );
  }

  current(): Snapshot {
    const active = this.#active;
    if (!active) throw new Error("generated config store: configuration is not initialized");
    return new Snapshot(active);
  }

  async #prepare(snapshot: ReleaseSnapshot, signal: AbortSignal): Promise<ManagedPreparedCandidate> {
    throwIfAborted(signal);
    const candidate = writableClone(this.#defaults.config());
    const secret0 = snapshot.secret("worker_token");
    if (!secret0 || secret0.entry.alias !== "worker_token" || secret0.entry.kind !== "secret") throw contractMismatch();
    const secretValue0 = new Secret(secret0.bytes(), {
      path: secret0.entry.path,
      version: secret0.entry.version,
      contentType: secret0.entry.contentType,
    });
    setProperty(candidate, "token", secretValue0);
    throwIfAborted(signal);
    const effectiveDefaults = writableClone(this.#defaults.config());
    setProperty(effectiveDefaults, "token", secretValue0.clone());
    let validatedCandidate: RootConfig;
    try {
      await this.#validate(candidate);
      throwIfAborted(signal);
      await this.#validate(effectiveDefaults);
      throwIfAborted(signal);
      assertSecret(candidate["token"], "worker_token");
      assertSecret(effectiveDefaults["token"], "worker_token");
      setProperty(candidate, "token", stripSecretBindingKey(candidate["token"]));
      setProperty(effectiveDefaults, "token", stripSecretBindingKey(effectiveDefaults["token"]));
      validatedCandidate = writableClone(candidate);
    } catch (cause) {
      if (signal.aborted) throw abortReason(signal);
      throw new CandidateError("config_validation_failed", cause);
    }
    throwIfAborted(signal);
    const defaultDifferences: FieldDifference[] = [];
    const restartRequiredFields: string[] = [];
    const active = this.#active;
    if (active) {
    }
    restartRequiredFields.sort();
    // Changed fields versus the previously applied generation feed onApplied. Secrets are path-only.
    const changed: FieldChange[] = [];
    if (active) {
      if (!sameSecretIdentity(active.get("token"), validatedCandidate["token"])) changed.push({ path: "worker_token", previous: null, current: null });
    }
    // Group documents feed observability only; an encoding failure must never reject a candidate.
    let groups: Readonly<Record<string, string>>;
    try {
      groups = encodeParameterGroups(validatedCandidate);
    } catch {
      groups = {};
    }
    const prepared = immutableSnapshot(validatedCandidate, ReleaseIdentity.from(snapshot));
    return {
      defaultDifferences,
      restartRequiredFields,
      changed,
      groups,
      publish: () => {
        this.#active = prepared;
      },
      abort: () => undefined,
    };
  }
}

function assertRootCoverage<T extends object, K extends PropertyKey>(
  ...missing: IsUnion<T> extends true ? [never] : [Exclude<keyof T, K>, Exclude<K, keyof T>] extends [never, never] ? [] : [never]
): void {
  void missing;
}

type IsUnion<T, Whole = T> = T extends unknown
  ? [Whole] extends [T]
    ? false
    : true
  : never;

function writableClone(value: RootConfig): RootConfig {
  const source = cloneConfig(value);
  const target = Object.create(Object.getPrototypeOf(source)) as object;
  for (const key of Reflect.ownKeys(source)) {
    const descriptor = Object.getOwnPropertyDescriptor(source, key);
    if (!descriptor || !("value" in descriptor)) {
      throw new TypeError("generated config store: accessor properties are not supported");
    }
    Object.defineProperty(target, key, { ...descriptor, writable: true, configurable: true });
  }
  return target as RootConfig;
}

function setProperty<T extends object, K extends keyof T>(target: T, key: K, value: T[K]): void {
  const current = Object.getOwnPropertyDescriptor(target, key);
  Object.defineProperty(target, key, {
    value: cloneConfig(value),
    enumerable: current?.enumerable ?? true,
    writable: true,
    configurable: true,
  });
}

function stripSecretBindingKey(value: Secret): Secret {
  const bytes = value.bytes();
  try {
    return new Secret(bytes, {
      path: value.path,
      version: value.version,
      contentType: value.contentType,
    });
  } finally {
    bytes.fill(0);
  }
}

function sameSecretIdentity(left: unknown, right: unknown): boolean {
  return (
    left instanceof Secret &&
    right instanceof Secret &&
    left.path === right.path &&
    left.version === right.version
  );
}

function assertSecret(value: unknown, alias: string): asserts value is Secret {
  if (!(value instanceof Secret)) {
    throw new TypeError("generated config store: validated secret " + alias + " must remain a Secret");
  }
}

function assertZeroSecret(value: unknown, alias: string): void {
  if (
    !(value instanceof Secret) ||
    !value.isEmpty ||
    value.path !== "" ||
    value.version !== 0n ||
    value.contentType !== ""
  ) {
    throw new TypeError("generated config store: secret default " + alias + " must be the zero Secret");
  }
}

function contractMismatch(): CandidateError {
  return new CandidateError(
    "config_contract_mismatch",
    new Error("generated config store: resolved release does not match contract"),
  );
}

function throwIfAborted(signal: AbortSignal): void {
  if (signal.aborted) throw abortReason(signal);
}

function abortReason(signal: AbortSignal): unknown {
  return signal.reason ?? new DOMException("Aborted", "AbortError");
}
