// Code generated by kms-config-gen; DO NOT EDIT.

package configkms

import (
	context "context"
	json "encoding/json"
	errors "errors"
	fmt "fmt"
	rootconfig "github.com/Suhaibinator/kms/examples/managed-config/config"
	configstore "github.com/Suhaibinator/kms/sdk/go/configstore"
	kmsclient "github.com/Suhaibinator/kms/sdk/go/kmsclient"
	atomic "sync/atomic"
	time "time"
)

const generatedSchemaSHA256 = "af7d501708d23e1494b16295629087859bda547ea50afa772507c7222aee760b"

var generatedContract = []configstore.ContractEntry{
	{Alias: "runtime", Kind: configstore.ContractKindParameter, ContentType: "json"},
	{Alias: "server", Kind: configstore.ContractKindParameter, ContentType: "json"},
	{Alias: "api_key", Kind: configstore.ContractKindSecret, ContentType: ""},
}

// Options configures the generated managed configuration store.
type Options struct {
	Release              string
	Defaults             func() *rootconfig.Config
	AllowDefaultMismatch bool
	OnDefaultMismatch    func(configstore.DefaultMismatchReport)
	OnCandidateRejected  func(configstore.CandidateRejectionReport)
	SecretTokenProvider  kmsclient.SecretTokenProvider
	ReconcileInterval    time.Duration
	MaxConcurrentFetches int
	InstanceID           string
}

// Store publishes whole immutable configuration generations.
type Store struct {
	active   atomic.Pointer[immutableGeneration]
	manager  *configstore.Manager
	defaults *rootconfig.Config
}

type immutableGeneration struct {
	config  *rootconfig.Config
	release configstore.ReleaseIdentity
}

// Snapshot captures exactly one immutable generation.
type Snapshot struct{ generation *immutableGeneration }

// HttpServerView is an immutable projection captured from a Snapshot.
type HttpServerView struct{ generation *immutableGeneration }

// RequestHandlerView is an immutable projection captured from a Snapshot.
type RequestHandlerView struct{ generation *immutableGeneration }

// EncodeParameterGroups encodes every complete non-secret parameter group from root.
// The returned documents use the same canonical encodings accepted by the generated store.
func EncodeParameterGroups(root *rootconfig.Config) (map[string]json.RawMessage, error) {
	if err := validateInlinePointers(root); err != nil {
		return nil, err
	}
	groups := make(map[string]json.RawMessage, 2)
	group0, err := configstore.EncodeGroup(root, groupFields0)
	if err != nil {
		return nil, fmt.Errorf("generated config store: encode parameter group runtime: %w", err)
	}
	groups["runtime"] = group0
	group1, err := configstore.EncodeGroup(root, groupFields1)
	if err != nil {
		return nil, fmt.Errorf("generated config store: encode parameter group server: %w", err)
	}
	groups["server"] = group1
	return groups, nil
}

// Start synchronously validates and publishes the initial release, then watches in the background.
func Start(ctx context.Context, client *kmsclient.Client, options Options) (*Store, error) {
	if options.Defaults == nil {
		return nil, errors.New("generated config store: Options.Defaults is required")
	}
	defaults := options.Defaults()
	if defaults == nil {
		return nil, errors.New("generated config store: Options.Defaults returned nil")
	}
	if err := validateInlinePointers(defaults); err != nil {
		return nil, err
	}
	if !defaults.APIKey.IsZero() || defaults.APIKey.Path() != "" || defaults.APIKey.Version() != 0 || defaults.APIKey.ContentType() != "" {
		return nil, fmt.Errorf("generated config store: default secret APIKey must be zero")
	}
	store := &Store{defaults: cloneRoot(defaults)}
	manager, err := configstore.Start(ctx, client, configstore.Options{
		Release:              options.Release,
		Contract:             generatedContract,
		AllowDefaultMismatch: options.AllowDefaultMismatch,
		OnDefaultMismatch:    options.OnDefaultMismatch,
		OnCandidateRejected:  options.OnCandidateRejected,
		SecretTokenProvider:  options.SecretTokenProvider,
		ReconcileInterval:    options.ReconcileInterval,
		MaxConcurrentFetches: options.MaxConcurrentFetches,
		InstanceID:           options.InstanceID,
	}, store.prepare)
	if err != nil {
		return nil, err
	}
	store.manager = manager
	return store, nil
}

func (s *Store) Status() configstore.Status { return s.manager.Status() }
func (s *Store) Stats() configstore.Stats   { return s.manager.Stats() }
func (s *Store) Wait() error                { return s.manager.Wait() }

func (s *Store) prepare(ctx context.Context, snapshot kmsclient.ReleaseSnapshot) (configstore.PreparedCandidate, error) {
	if err := ctx.Err(); err != nil {
		return configstore.PreparedCandidate{}, err
	}
	candidate := cloneRoot(s.defaults)
	parameter0, ok := snapshot.Parameter("runtime")
	if !ok {
		return configstore.PreparedCandidate{}, configstore.Reject(configstore.RejectConfigContractMismatch, fmt.Errorf("missing parameter group runtime"))
	}
	if err := configstore.DecodeGroup(parameter0.Value(), candidate, groupFields0); err != nil {
		return configstore.PreparedCandidate{}, configstore.RejectDecode("runtime", err)
	}
	parameter1, ok := snapshot.Parameter("server")
	if !ok {
		return configstore.PreparedCandidate{}, configstore.Reject(configstore.RejectConfigContractMismatch, fmt.Errorf("missing parameter group server"))
	}
	if err := configstore.DecodeGroup(parameter1.Value(), candidate, groupFields1); err != nil {
		return configstore.PreparedCandidate{}, configstore.RejectDecode("server", err)
	}
	secret0, ok := snapshot.Secret("api_key")
	if !ok {
		return configstore.PreparedCandidate{}, configstore.Reject(configstore.RejectConfigContractMismatch, fmt.Errorf("missing secret alias api_key"))
	}
	candidate.APIKey = secret0.Clone()
	if err := candidate.Validate(); err != nil {
		return configstore.PreparedCandidate{}, configstore.Reject(configstore.RejectConfigValidationFailed, fmt.Errorf("validate KMS configuration: %w", err))
	}
	if err := validateInlinePointers(candidate); err != nil {
		return configstore.PreparedCandidate{}, configstore.Reject(configstore.RejectConfigValidationFailed, err)
	}
	effectiveDefaults := cloneRoot(s.defaults)
	effectiveDefaults.APIKey = secret0.Clone()
	if err := effectiveDefaults.Validate(); err != nil {
		return configstore.PreparedCandidate{}, configstore.Reject(configstore.RejectConfigValidationFailed, fmt.Errorf("validate effective application defaults: %w", err))
	}
	if err := validateInlinePointers(effectiveDefaults); err != nil {
		return configstore.PreparedCandidate{}, configstore.Reject(configstore.RejectConfigValidationFailed, err)
	}
	// Validation is application code and may mutate its receiver. Clone once more before retaining either value.
	candidate = cloneRoot(candidate)
	effectiveDefaults = cloneRoot(effectiveDefaults)
	differences := make([]configstore.FieldDifference, 0)
	if !equalValue0(effectiveDefaults.Greeting, candidate.Greeting) {
		differences = append(differences, configstore.FieldDifference{Path: "runtime.greeting", Expected: reportValue0(effectiveDefaults.Greeting), Actual: reportValue0(candidate.Greeting)})
	}
	if !equalValue1(effectiveDefaults.RequestLimit, candidate.RequestLimit) {
		differences = append(differences, configstore.FieldDifference{Path: "runtime.request_limit", Expected: reportValue1(effectiveDefaults.RequestLimit), Actual: reportValue1(candidate.RequestLimit)})
	}
	if !equalValue0(effectiveDefaults.ListenAddress, candidate.ListenAddress) {
		differences = append(differences, configstore.FieldDifference{Path: "server.listen_address", Expected: reportValue0(effectiveDefaults.ListenAddress), Actual: reportValue0(candidate.ListenAddress)})
	}
	restartRequired := make([]string, 0)
	active := s.active.Load()
	if active != nil {
		if !equalValue0(candidate.ListenAddress, active.config.ListenAddress) {
			restartRequired = append(restartRequired, "server.listen_address")
		}
	}
	generation := &immutableGeneration{config: candidate, release: configstore.ReleaseIdentityFromSnapshot(snapshot)}
	return configstore.PreparedCandidate{
		Publish:               func() { s.active.Store(generation) },
		Abort:                 func() {},
		DefaultDifferences:    differences,
		RestartRequiredFields: restartRequired,
	}, nil
}

var groupFields0 = []configstore.FieldCodec{
	{JSONName: "greeting", FieldIndex: []int{1}, Value: configstore.ValueCodec{Kind: configstore.CodecString}},
	{JSONName: "request_limit", FieldIndex: []int{2}, Value: configstore.ValueCodec{Kind: configstore.CodecInt, Bits: 32}},
}

var groupFields1 = []configstore.FieldCodec{
	{JSONName: "listen_address", FieldIndex: []int{0}, Value: configstore.ValueCodec{Kind: configstore.CodecString}},
}

// Current performs exactly one atomic load and captures that generation.
func (s *Store) Current() Snapshot {
	generation := s.active.Load()
	return Snapshot{generation: generation}
}

func (s Snapshot) Release() configstore.ReleaseIdentity { return s.generation.release }

// Config returns a defensive copy of this complete immutable generation.
// Use generated views instead when reading hot configuration in an operation path.
func (s Snapshot) Config() *rootconfig.Config { return cloneRoot(s.generation.config) }

func (s Snapshot) HttpServer() HttpServerView { return HttpServerView{generation: s.generation} }
func (s Snapshot) RequestHandler() RequestHandlerView {
	return RequestHandlerView{generation: s.generation}
}

func (v HttpServerView) ListenAddress() string { return v.generation.config.ListenAddress }

func (v RequestHandlerView) APIKey() kmsclient.Secret { return v.generation.config.APIKey.Clone() }
func (v RequestHandlerView) Greeting() string         { return v.generation.config.Greeting }
func (v RequestHandlerView) RequestLimit() int        { return v.generation.config.RequestLimit }

func cloneRoot(value *rootconfig.Config) *rootconfig.Config {
	if value == nil {
		return nil
	}
	// Root cloning is preparation-only. It also isolates excluded fields that generated getters never expose.
	out := configstore.Clone(*value)
	out.APIKey = value.APIKey.Clone()
	return &out
}

func validateInlinePointers(value *rootconfig.Config) error {
	if value == nil {
		return errors.New("generated config store: configuration root is nil")
	}
	return nil
}

func cloneValue0(value string) string {
	return value
}

func equalValue0(left, right string) bool {
	return left == right
}

func reportValue0(value string) any {
	return value
}

func cloneValue1(value int) int {
	return value
}

func equalValue1(left, right int) bool {
	return left == right
}

func reportValue1(value int) any {
	return value
}
