# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from kms_paramstore._gen import kms_pb2 as kms_dot_v1_dot_kms__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kms/v1/kms_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ParameterServiceStub:
    """---------------------------------------------------------------------------
    ParameterService
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetParameter = channel.unary_unary(
                '/kms.v1.ParameterService/GetParameter',
                request_serializer=kms_dot_v1_dot_kms__pb2.GetParameterRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.GetParameterResponse.FromString,
                _registered_method=True)
        self.PutParameter = channel.unary_unary(
                '/kms.v1.ParameterService/PutParameter',
                request_serializer=kms_dot_v1_dot_kms__pb2.PutParameterRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.PutParameterResponse.FromString,
                _registered_method=True)
        self.ListParameters = channel.unary_unary(
                '/kms.v1.ParameterService/ListParameters',
                request_serializer=kms_dot_v1_dot_kms__pb2.ListParametersRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.ListParametersResponse.FromString,
                _registered_method=True)
        self.DeleteParameter = channel.unary_unary(
                '/kms.v1.ParameterService/DeleteParameter',
                request_serializer=kms_dot_v1_dot_kms__pb2.DeleteParameterRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.DeleteParameterResponse.FromString,
                _registered_method=True)
        self.GetParameterMetadata = channel.unary_unary(
                '/kms.v1.ParameterService/GetParameterMetadata',
                request_serializer=kms_dot_v1_dot_kms__pb2.GetParameterMetadataRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.GetParameterMetadataResponse.FromString,
                _registered_method=True)


class ParameterServiceServicer:
    """---------------------------------------------------------------------------
    ParameterService
    ---------------------------------------------------------------------------

    """

    def GetParameter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutParameter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListParameters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteParameter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetParameterMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ParameterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetParameter': grpc.unary_unary_rpc_method_handler(
                    servicer.GetParameter,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.GetParameterRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.GetParameterResponse.SerializeToString,
            ),
            'PutParameter': grpc.unary_unary_rpc_method_handler(
                    servicer.PutParameter,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.PutParameterRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.PutParameterResponse.SerializeToString,
            ),
            'ListParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.ListParameters,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.ListParametersRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.ListParametersResponse.SerializeToString,
            ),
            'DeleteParameter': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteParameter,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.DeleteParameterRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.DeleteParameterResponse.SerializeToString,
            ),
            'GetParameterMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetParameterMetadata,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.GetParameterMetadataRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.GetParameterMetadataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kms.v1.ParameterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kms.v1.ParameterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ParameterService:
    """---------------------------------------------------------------------------
    ParameterService
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def GetParameter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.ParameterService/GetParameter',
            kms_dot_v1_dot_kms__pb2.GetParameterRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.GetParameterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutParameter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.ParameterService/PutParameter',
            kms_dot_v1_dot_kms__pb2.PutParameterRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.PutParameterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.ParameterService/ListParameters',
            kms_dot_v1_dot_kms__pb2.ListParametersRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.ListParametersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteParameter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.ParameterService/DeleteParameter',
            kms_dot_v1_dot_kms__pb2.DeleteParameterRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.DeleteParameterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetParameterMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.ParameterService/GetParameterMetadata',
            kms_dot_v1_dot_kms__pb2.GetParameterMetadataRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.GetParameterMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SecretServiceStub:
    """---------------------------------------------------------------------------
    SecretService
    ---------------------------------------------------------------------------

    Authentication travels in gRPC metadata:
    "authorization":      "Bearer <per-client token>"
    "x-kms-secret-token": "<per-secret access token>"  (when required / client-bound)

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSecret = channel.unary_unary(
                '/kms.v1.SecretService/GetSecret',
                request_serializer=kms_dot_v1_dot_kms__pb2.GetSecretRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.GetSecretResponse.FromString,
                _registered_method=True)
        self.PutSecret = channel.unary_unary(
                '/kms.v1.SecretService/PutSecret',
                request_serializer=kms_dot_v1_dot_kms__pb2.PutSecretRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.PutSecretResponse.FromString,
                _registered_method=True)
        self.ListSecrets = channel.unary_unary(
                '/kms.v1.SecretService/ListSecrets',
                request_serializer=kms_dot_v1_dot_kms__pb2.ListSecretsRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.ListSecretsResponse.FromString,
                _registered_method=True)
        self.DeleteSecret = channel.unary_unary(
                '/kms.v1.SecretService/DeleteSecret',
                request_serializer=kms_dot_v1_dot_kms__pb2.DeleteSecretRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.DeleteSecretResponse.FromString,
                _registered_method=True)
        self.DisableSecret = channel.unary_unary(
                '/kms.v1.SecretService/DisableSecret',
                request_serializer=kms_dot_v1_dot_kms__pb2.DisableSecretRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.DisableSecretResponse.FromString,
                _registered_method=True)
        self.DestroySecretVersion = channel.unary_unary(
                '/kms.v1.SecretService/DestroySecretVersion',
                request_serializer=kms_dot_v1_dot_kms__pb2.DestroySecretVersionRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.DestroySecretVersionResponse.FromString,
                _registered_method=True)
        self.GetSecretMetadata = channel.unary_unary(
                '/kms.v1.SecretService/GetSecretMetadata',
                request_serializer=kms_dot_v1_dot_kms__pb2.GetSecretMetadataRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.GetSecretMetadataResponse.FromString,
                _registered_method=True)
        self.PromoteSecretVersion = channel.unary_unary(
                '/kms.v1.SecretService/PromoteSecretVersion',
                request_serializer=kms_dot_v1_dot_kms__pb2.PromoteSecretVersionRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.PromoteSecretVersionResponse.FromString,
                _registered_method=True)


class SecretServiceServicer:
    """---------------------------------------------------------------------------
    SecretService
    ---------------------------------------------------------------------------

    Authentication travels in gRPC metadata:
    "authorization":      "Bearer <per-client token>"
    "x-kms-secret-token": "<per-secret access token>"  (when required / client-bound)

    """

    def GetSecret(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutSecret(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSecrets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSecret(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisableSecret(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroySecretVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSecretMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PromoteSecretVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SecretServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSecret,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.GetSecretRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.GetSecretResponse.SerializeToString,
            ),
            'PutSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.PutSecret,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.PutSecretRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.PutSecretResponse.SerializeToString,
            ),
            'ListSecrets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSecrets,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.ListSecretsRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.ListSecretsResponse.SerializeToString,
            ),
            'DeleteSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSecret,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.DeleteSecretRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.DeleteSecretResponse.SerializeToString,
            ),
            'DisableSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.DisableSecret,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.DisableSecretRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.DisableSecretResponse.SerializeToString,
            ),
            'DestroySecretVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroySecretVersion,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.DestroySecretVersionRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.DestroySecretVersionResponse.SerializeToString,
            ),
            'GetSecretMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSecretMetadata,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.GetSecretMetadataRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.GetSecretMetadataResponse.SerializeToString,
            ),
            'PromoteSecretVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.PromoteSecretVersion,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.PromoteSecretVersionRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.PromoteSecretVersionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kms.v1.SecretService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kms.v1.SecretService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SecretService:
    """---------------------------------------------------------------------------
    SecretService
    ---------------------------------------------------------------------------

    Authentication travels in gRPC metadata:
    "authorization":      "Bearer <per-client token>"
    "x-kms-secret-token": "<per-secret access token>"  (when required / client-bound)

    """

    @staticmethod
    def GetSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.SecretService/GetSecret',
            kms_dot_v1_dot_kms__pb2.GetSecretRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.GetSecretResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.SecretService/PutSecret',
            kms_dot_v1_dot_kms__pb2.PutSecretRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.PutSecretResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSecrets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.SecretService/ListSecrets',
            kms_dot_v1_dot_kms__pb2.ListSecretsRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.ListSecretsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.SecretService/DeleteSecret',
            kms_dot_v1_dot_kms__pb2.DeleteSecretRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.DeleteSecretResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisableSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.SecretService/DisableSecret',
            kms_dot_v1_dot_kms__pb2.DisableSecretRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.DisableSecretResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DestroySecretVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.SecretService/DestroySecretVersion',
            kms_dot_v1_dot_kms__pb2.DestroySecretVersionRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.DestroySecretVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSecretMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.SecretService/GetSecretMetadata',
            kms_dot_v1_dot_kms__pb2.GetSecretMetadataRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.GetSecretMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PromoteSecretVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.SecretService/PromoteSecretVersion',
            kms_dot_v1_dot_kms__pb2.PromoteSecretVersionRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.PromoteSecretVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WatchServiceStub:
    """---------------------------------------------------------------------------
    WatchService
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Subscribe = channel.stream_stream(
                '/kms.v1.WatchService/Subscribe',
                request_serializer=kms_dot_v1_dot_kms__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.SubscribeEvent.FromString,
                _registered_method=True)
        self.WatchParameter = channel.unary_stream(
                '/kms.v1.WatchService/WatchParameter',
                request_serializer=kms_dot_v1_dot_kms__pb2.WatchParameterRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.SubscribeEvent.FromString,
                _registered_method=True)
        self.WatchNamespace = channel.unary_stream(
                '/kms.v1.WatchService/WatchNamespace',
                request_serializer=kms_dot_v1_dot_kms__pb2.WatchNamespaceRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.SubscribeEvent.FromString,
                _registered_method=True)


class WatchServiceServicer:
    """---------------------------------------------------------------------------
    WatchService
    ---------------------------------------------------------------------------

    """

    def Subscribe(self, request_iterator, context):
        """Subscribe is the primary hot-reload mechanism. The client declares the
        paths/prefixes it wants and its last-applied revision; the server streams
        an initial snapshot (or delta), then pushes events as values change,
        interleaved with heartbeats.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchParameter(self, request, context):
        """Single-resource conveniences built on the same event model.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchNamespace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WatchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Subscribe': grpc.stream_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.SubscribeRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.SubscribeEvent.SerializeToString,
            ),
            'WatchParameter': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchParameter,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.WatchParameterRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.SubscribeEvent.SerializeToString,
            ),
            'WatchNamespace': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchNamespace,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.WatchNamespaceRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.SubscribeEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kms.v1.WatchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kms.v1.WatchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WatchService:
    """---------------------------------------------------------------------------
    WatchService
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def Subscribe(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/kms.v1.WatchService/Subscribe',
            kms_dot_v1_dot_kms__pb2.SubscribeRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.SubscribeEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchParameter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kms.v1.WatchService/WatchParameter',
            kms_dot_v1_dot_kms__pb2.WatchParameterRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.SubscribeEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchNamespace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kms.v1.WatchService/WatchNamespace',
            kms_dot_v1_dot_kms__pb2.WatchNamespaceRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.SubscribeEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AdminServiceStub:
    """---------------------------------------------------------------------------
    AdminService
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateNamespace = channel.unary_unary(
                '/kms.v1.AdminService/CreateNamespace',
                request_serializer=kms_dot_v1_dot_kms__pb2.CreateNamespaceRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.CreateNamespaceResponse.FromString,
                _registered_method=True)
        self.ListNamespaces = channel.unary_unary(
                '/kms.v1.AdminService/ListNamespaces',
                request_serializer=kms_dot_v1_dot_kms__pb2.ListNamespacesRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.ListNamespacesResponse.FromString,
                _registered_method=True)
        self.CreatePolicy = channel.unary_unary(
                '/kms.v1.AdminService/CreatePolicy',
                request_serializer=kms_dot_v1_dot_kms__pb2.CreatePolicyRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.CreatePolicyResponse.FromString,
                _registered_method=True)
        self.UpdatePolicy = channel.unary_unary(
                '/kms.v1.AdminService/UpdatePolicy',
                request_serializer=kms_dot_v1_dot_kms__pb2.UpdatePolicyRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.UpdatePolicyResponse.FromString,
                _registered_method=True)
        self.DeletePolicy = channel.unary_unary(
                '/kms.v1.AdminService/DeletePolicy',
                request_serializer=kms_dot_v1_dot_kms__pb2.DeletePolicyRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.DeletePolicyResponse.FromString,
                _registered_method=True)
        self.ListPolicies = channel.unary_unary(
                '/kms.v1.AdminService/ListPolicies',
                request_serializer=kms_dot_v1_dot_kms__pb2.ListPoliciesRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.ListPoliciesResponse.FromString,
                _registered_method=True)
        self.CreateIdentity = channel.unary_unary(
                '/kms.v1.AdminService/CreateIdentity',
                request_serializer=kms_dot_v1_dot_kms__pb2.CreateIdentityRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.CreateIdentityResponse.FromString,
                _registered_method=True)
        self.ListIdentities = channel.unary_unary(
                '/kms.v1.AdminService/ListIdentities',
                request_serializer=kms_dot_v1_dot_kms__pb2.ListIdentitiesRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.ListIdentitiesResponse.FromString,
                _registered_method=True)
        self.RevokeIdentity = channel.unary_unary(
                '/kms.v1.AdminService/RevokeIdentity',
                request_serializer=kms_dot_v1_dot_kms__pb2.RevokeIdentityRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.RevokeIdentityResponse.FromString,
                _registered_method=True)
        self.RotateIdentityToken = channel.unary_unary(
                '/kms.v1.AdminService/RotateIdentityToken',
                request_serializer=kms_dot_v1_dot_kms__pb2.RotateIdentityTokenRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.RotateIdentityTokenResponse.FromString,
                _registered_method=True)
        self.ListAuditEvents = channel.unary_unary(
                '/kms.v1.AdminService/ListAuditEvents',
                request_serializer=kms_dot_v1_dot_kms__pb2.ListAuditEventsRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.ListAuditEventsResponse.FromString,
                _registered_method=True)
        self.ListSubscribers = channel.unary_unary(
                '/kms.v1.AdminService/ListSubscribers',
                request_serializer=kms_dot_v1_dot_kms__pb2.ListSubscribersRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.ListSubscribersResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/kms.v1.AdminService/Health',
                request_serializer=kms_dot_v1_dot_kms__pb2.HealthRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.HealthResponse.FromString,
                _registered_method=True)


class AdminServiceServicer:
    """---------------------------------------------------------------------------
    AdminService
    ---------------------------------------------------------------------------

    """

    def CreateNamespace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNamespaces(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPolicies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateIdentity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListIdentities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeIdentity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RotateIdentityToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAuditEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSubscribers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateNamespace': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNamespace,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.CreateNamespaceRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.CreateNamespaceResponse.SerializeToString,
            ),
            'ListNamespaces': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNamespaces,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.ListNamespacesRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.ListNamespacesResponse.SerializeToString,
            ),
            'CreatePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePolicy,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.CreatePolicyRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.CreatePolicyResponse.SerializeToString,
            ),
            'UpdatePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePolicy,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.UpdatePolicyRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.UpdatePolicyResponse.SerializeToString,
            ),
            'DeletePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePolicy,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.DeletePolicyRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.DeletePolicyResponse.SerializeToString,
            ),
            'ListPolicies': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPolicies,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.ListPoliciesRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.ListPoliciesResponse.SerializeToString,
            ),
            'CreateIdentity': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateIdentity,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.CreateIdentityRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.CreateIdentityResponse.SerializeToString,
            ),
            'ListIdentities': grpc.unary_unary_rpc_method_handler(
                    servicer.ListIdentities,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.ListIdentitiesRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.ListIdentitiesResponse.SerializeToString,
            ),
            'RevokeIdentity': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeIdentity,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.RevokeIdentityRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.RevokeIdentityResponse.SerializeToString,
            ),
            'RotateIdentityToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RotateIdentityToken,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.RotateIdentityTokenRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.RotateIdentityTokenResponse.SerializeToString,
            ),
            'ListAuditEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAuditEvents,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.ListAuditEventsRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.ListAuditEventsResponse.SerializeToString,
            ),
            'ListSubscribers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSubscribers,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.ListSubscribersRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.ListSubscribersResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.HealthRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kms.v1.AdminService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kms.v1.AdminService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdminService:
    """---------------------------------------------------------------------------
    AdminService
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def CreateNamespace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.AdminService/CreateNamespace',
            kms_dot_v1_dot_kms__pb2.CreateNamespaceRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.CreateNamespaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNamespaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.AdminService/ListNamespaces',
            kms_dot_v1_dot_kms__pb2.ListNamespacesRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.ListNamespacesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.AdminService/CreatePolicy',
            kms_dot_v1_dot_kms__pb2.CreatePolicyRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.CreatePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.AdminService/UpdatePolicy',
            kms_dot_v1_dot_kms__pb2.UpdatePolicyRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.UpdatePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.AdminService/DeletePolicy',
            kms_dot_v1_dot_kms__pb2.DeletePolicyRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.DeletePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPolicies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.AdminService/ListPolicies',
            kms_dot_v1_dot_kms__pb2.ListPoliciesRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.ListPoliciesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateIdentity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.AdminService/CreateIdentity',
            kms_dot_v1_dot_kms__pb2.CreateIdentityRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.CreateIdentityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListIdentities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.AdminService/ListIdentities',
            kms_dot_v1_dot_kms__pb2.ListIdentitiesRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.ListIdentitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeIdentity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.AdminService/RevokeIdentity',
            kms_dot_v1_dot_kms__pb2.RevokeIdentityRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.RevokeIdentityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RotateIdentityToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.AdminService/RotateIdentityToken',
            kms_dot_v1_dot_kms__pb2.RotateIdentityTokenRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.RotateIdentityTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAuditEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.AdminService/ListAuditEvents',
            kms_dot_v1_dot_kms__pb2.ListAuditEventsRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.ListAuditEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSubscribers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.AdminService/ListSubscribers',
            kms_dot_v1_dot_kms__pb2.ListSubscribersRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.ListSubscribersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.AdminService/Health',
            kms_dot_v1_dot_kms__pb2.HealthRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
