# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from kms_paramstore._gen import kms_pb2 as kms_dot_v1_dot_kms__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kms/v1/kms_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ParameterServiceStub:
    """---------------------------------------------------------------------------
    ParameterService
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetParameter = channel.unary_unary(
                '/kms.v1.ParameterService/GetParameter',
                request_serializer=kms_dot_v1_dot_kms__pb2.GetParameterRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.GetParameterResponse.FromString,
                _registered_method=True)
        self.PutParameter = channel.unary_unary(
                '/kms.v1.ParameterService/PutParameter',
                request_serializer=kms_dot_v1_dot_kms__pb2.PutParameterRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.PutParameterResponse.FromString,
                _registered_method=True)
        self.ListParameters = channel.unary_unary(
                '/kms.v1.ParameterService/ListParameters',
                request_serializer=kms_dot_v1_dot_kms__pb2.ListParametersRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.ListParametersResponse.FromString,
                _registered_method=True)
        self.DeleteParameter = channel.unary_unary(
                '/kms.v1.ParameterService/DeleteParameter',
                request_serializer=kms_dot_v1_dot_kms__pb2.DeleteParameterRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.DeleteParameterResponse.FromString,
                _registered_method=True)
        self.GetParameterMetadata = channel.unary_unary(
                '/kms.v1.ParameterService/GetParameterMetadata',
                request_serializer=kms_dot_v1_dot_kms__pb2.GetParameterMetadataRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.GetParameterMetadataResponse.FromString,
                _registered_method=True)


class ParameterServiceServicer:
    """---------------------------------------------------------------------------
    ParameterService
    ---------------------------------------------------------------------------

    """

    def GetParameter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutParameter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListParameters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteParameter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetParameterMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ParameterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetParameter': grpc.unary_unary_rpc_method_handler(
                    servicer.GetParameter,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.GetParameterRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.GetParameterResponse.SerializeToString,
            ),
            'PutParameter': grpc.unary_unary_rpc_method_handler(
                    servicer.PutParameter,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.PutParameterRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.PutParameterResponse.SerializeToString,
            ),
            'ListParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.ListParameters,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.ListParametersRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.ListParametersResponse.SerializeToString,
            ),
            'DeleteParameter': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteParameter,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.DeleteParameterRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.DeleteParameterResponse.SerializeToString,
            ),
            'GetParameterMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetParameterMetadata,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.GetParameterMetadataRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.GetParameterMetadataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kms.v1.ParameterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kms.v1.ParameterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ParameterService:
    """---------------------------------------------------------------------------
    ParameterService
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def GetParameter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.ParameterService/GetParameter',
            kms_dot_v1_dot_kms__pb2.GetParameterRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.GetParameterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutParameter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.ParameterService/PutParameter',
            kms_dot_v1_dot_kms__pb2.PutParameterRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.PutParameterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.ParameterService/ListParameters',
            kms_dot_v1_dot_kms__pb2.ListParametersRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.ListParametersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteParameter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.ParameterService/DeleteParameter',
            kms_dot_v1_dot_kms__pb2.DeleteParameterRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.DeleteParameterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetParameterMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.ParameterService/GetParameterMetadata',
            kms_dot_v1_dot_kms__pb2.GetParameterMetadataRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.GetParameterMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SecretServiceStub:
    """---------------------------------------------------------------------------
    SecretService
    ---------------------------------------------------------------------------

    Identity authentication travels in standard gRPC metadata:
    "authorization": "Bearer <per-client token>"
    Per-secret credentials are fields on only the requests that consume them.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSecret = channel.unary_unary(
                '/kms.v1.SecretService/GetSecret',
                request_serializer=kms_dot_v1_dot_kms__pb2.GetSecretRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.GetSecretResponse.FromString,
                _registered_method=True)
        self.PutSecret = channel.unary_unary(
                '/kms.v1.SecretService/PutSecret',
                request_serializer=kms_dot_v1_dot_kms__pb2.PutSecretRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.PutSecretResponse.FromString,
                _registered_method=True)
        self.ListSecrets = channel.unary_unary(
                '/kms.v1.SecretService/ListSecrets',
                request_serializer=kms_dot_v1_dot_kms__pb2.ListSecretsRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.ListSecretsResponse.FromString,
                _registered_method=True)
        self.DeleteSecret = channel.unary_unary(
                '/kms.v1.SecretService/DeleteSecret',
                request_serializer=kms_dot_v1_dot_kms__pb2.DeleteSecretRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.DeleteSecretResponse.FromString,
                _registered_method=True)
        self.DisableSecret = channel.unary_unary(
                '/kms.v1.SecretService/DisableSecret',
                request_serializer=kms_dot_v1_dot_kms__pb2.DisableSecretRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.DisableSecretResponse.FromString,
                _registered_method=True)
        self.DestroySecretVersion = channel.unary_unary(
                '/kms.v1.SecretService/DestroySecretVersion',
                request_serializer=kms_dot_v1_dot_kms__pb2.DestroySecretVersionRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.DestroySecretVersionResponse.FromString,
                _registered_method=True)
        self.GetSecretMetadata = channel.unary_unary(
                '/kms.v1.SecretService/GetSecretMetadata',
                request_serializer=kms_dot_v1_dot_kms__pb2.GetSecretMetadataRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.GetSecretMetadataResponse.FromString,
                _registered_method=True)
        self.PromoteSecretVersion = channel.unary_unary(
                '/kms.v1.SecretService/PromoteSecretVersion',
                request_serializer=kms_dot_v1_dot_kms__pb2.PromoteSecretVersionRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.PromoteSecretVersionResponse.FromString,
                _registered_method=True)


class SecretServiceServicer:
    """---------------------------------------------------------------------------
    SecretService
    ---------------------------------------------------------------------------

    Identity authentication travels in standard gRPC metadata:
    "authorization": "Bearer <per-client token>"
    Per-secret credentials are fields on only the requests that consume them.

    """

    def GetSecret(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutSecret(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSecrets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSecret(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisableSecret(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroySecretVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSecretMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PromoteSecretVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SecretServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSecret,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.GetSecretRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.GetSecretResponse.SerializeToString,
            ),
            'PutSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.PutSecret,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.PutSecretRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.PutSecretResponse.SerializeToString,
            ),
            'ListSecrets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSecrets,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.ListSecretsRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.ListSecretsResponse.SerializeToString,
            ),
            'DeleteSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSecret,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.DeleteSecretRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.DeleteSecretResponse.SerializeToString,
            ),
            'DisableSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.DisableSecret,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.DisableSecretRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.DisableSecretResponse.SerializeToString,
            ),
            'DestroySecretVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroySecretVersion,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.DestroySecretVersionRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.DestroySecretVersionResponse.SerializeToString,
            ),
            'GetSecretMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSecretMetadata,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.GetSecretMetadataRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.GetSecretMetadataResponse.SerializeToString,
            ),
            'PromoteSecretVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.PromoteSecretVersion,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.PromoteSecretVersionRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.PromoteSecretVersionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kms.v1.SecretService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kms.v1.SecretService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SecretService:
    """---------------------------------------------------------------------------
    SecretService
    ---------------------------------------------------------------------------

    Identity authentication travels in standard gRPC metadata:
    "authorization": "Bearer <per-client token>"
    Per-secret credentials are fields on only the requests that consume them.

    """

    @staticmethod
    def GetSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.SecretService/GetSecret',
            kms_dot_v1_dot_kms__pb2.GetSecretRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.GetSecretResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.SecretService/PutSecret',
            kms_dot_v1_dot_kms__pb2.PutSecretRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.PutSecretResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSecrets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.SecretService/ListSecrets',
            kms_dot_v1_dot_kms__pb2.ListSecretsRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.ListSecretsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.SecretService/DeleteSecret',
            kms_dot_v1_dot_kms__pb2.DeleteSecretRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.DeleteSecretResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisableSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.SecretService/DisableSecret',
            kms_dot_v1_dot_kms__pb2.DisableSecretRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.DisableSecretResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DestroySecretVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.SecretService/DestroySecretVersion',
            kms_dot_v1_dot_kms__pb2.DestroySecretVersionRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.DestroySecretVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSecretMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.SecretService/GetSecretMetadata',
            kms_dot_v1_dot_kms__pb2.GetSecretMetadataRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.GetSecretMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PromoteSecretVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.SecretService/PromoteSecretVersion',
            kms_dot_v1_dot_kms__pb2.PromoteSecretVersionRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.PromoteSecretVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WatchServiceStub:
    """---------------------------------------------------------------------------
    WatchService
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Subscribe = channel.stream_stream(
                '/kms.v1.WatchService/Subscribe',
                request_serializer=kms_dot_v1_dot_kms__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.SubscribeEvent.FromString,
                _registered_method=True)


class WatchServiceServicer:
    """---------------------------------------------------------------------------
    WatchService
    ---------------------------------------------------------------------------

    """

    def Subscribe(self, request_iterator, context):
        """Subscribe is the hot-reload mechanism. The client declares the namespaces
        it wants and its last-applied revision; the server streams an initial
        snapshot (or delta), then pushes EVERY change in those namespaces the
        caller is authorized for, interleaved with heartbeats. Authorization is
        checked once per namespace at registration; there is no key-level
        filtering — a subscriber to a namespace receives all of its changes and
        routes them client-side.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WatchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Subscribe': grpc.stream_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.SubscribeRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.SubscribeEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kms.v1.WatchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kms.v1.WatchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WatchService:
    """---------------------------------------------------------------------------
    WatchService
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def Subscribe(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/kms.v1.WatchService/Subscribe',
            kms_dot_v1_dot_kms__pb2.SubscribeRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.SubscribeEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ConfigurationReleaseServiceStub:
    """---------------------------------------------------------------------------
    ConfigurationReleaseService
    ---------------------------------------------------------------------------

    Configuration releases are immutable namespace-scoped manifests. They
    contain exact parameter/secret version references and non-sensitive
    metadata only; values and secret access tokens are never embedded.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRelease = channel.unary_unary(
                '/kms.v1.ConfigurationReleaseService/CreateRelease',
                request_serializer=kms_dot_v1_dot_kms__pb2.CreateReleaseRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.CreateReleaseResponse.FromString,
                _registered_method=True)
        self.ValidateRelease = channel.unary_unary(
                '/kms.v1.ConfigurationReleaseService/ValidateRelease',
                request_serializer=kms_dot_v1_dot_kms__pb2.ValidateReleaseRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.ValidateReleaseResponse.FromString,
                _registered_method=True)
        self.ActivateRelease = channel.unary_unary(
                '/kms.v1.ConfigurationReleaseService/ActivateRelease',
                request_serializer=kms_dot_v1_dot_kms__pb2.ActivateReleaseRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.ActivateReleaseResponse.FromString,
                _registered_method=True)
        self.GetRelease = channel.unary_unary(
                '/kms.v1.ConfigurationReleaseService/GetRelease',
                request_serializer=kms_dot_v1_dot_kms__pb2.GetReleaseRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.GetReleaseResponse.FromString,
                _registered_method=True)
        self.GetActiveRelease = channel.unary_unary(
                '/kms.v1.ConfigurationReleaseService/GetActiveRelease',
                request_serializer=kms_dot_v1_dot_kms__pb2.GetActiveReleaseRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.GetActiveReleaseResponse.FromString,
                _registered_method=True)
        self.ListReleases = channel.unary_unary(
                '/kms.v1.ConfigurationReleaseService/ListReleases',
                request_serializer=kms_dot_v1_dot_kms__pb2.ListReleasesRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.ListReleasesResponse.FromString,
                _registered_method=True)
        self.WatchRelease = channel.stream_stream(
                '/kms.v1.ConfigurationReleaseService/WatchRelease',
                request_serializer=kms_dot_v1_dot_kms__pb2.WatchReleaseRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.WatchReleaseEvent.FromString,
                _registered_method=True)
        self.VerifyReleaseDefaults = channel.unary_unary(
                '/kms.v1.ConfigurationReleaseService/VerifyReleaseDefaults',
                request_serializer=kms_dot_v1_dot_kms__pb2.VerifyReleaseDefaultsRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.VerifyReleaseDefaultsResponse.FromString,
                _registered_method=True)


class ConfigurationReleaseServiceServicer:
    """---------------------------------------------------------------------------
    ConfigurationReleaseService
    ---------------------------------------------------------------------------

    Configuration releases are immutable namespace-scoped manifests. They
    contain exact parameter/secret version references and non-sensitive
    metadata only; values and secret access tokens are never embedded.
    """

    def CreateRelease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateRelease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActivateRelease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRelease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActiveRelease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListReleases(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchRelease(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyReleaseDefaults(self, request, context):
        """VerifyReleaseDefaults compares caller-supplied canonical content hashes of
        an application's source-owned defaults with the parameters pinned by the
        active release. The request and response are value-free: only aliases,
        content types, hashes, and bounded verdicts travel over the wire, and the
        server never echoes a stored value, digest, or hash. Secret aliases are
        structurally excluded and reported as secret_alias. Requires the
        configuration-release:verify-defaults operation and is rate limited per
        identity.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConfigurationReleaseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRelease': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRelease,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.CreateReleaseRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.CreateReleaseResponse.SerializeToString,
            ),
            'ValidateRelease': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateRelease,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.ValidateReleaseRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.ValidateReleaseResponse.SerializeToString,
            ),
            'ActivateRelease': grpc.unary_unary_rpc_method_handler(
                    servicer.ActivateRelease,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.ActivateReleaseRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.ActivateReleaseResponse.SerializeToString,
            ),
            'GetRelease': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRelease,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.GetReleaseRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.GetReleaseResponse.SerializeToString,
            ),
            'GetActiveRelease': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActiveRelease,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.GetActiveReleaseRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.GetActiveReleaseResponse.SerializeToString,
            ),
            'ListReleases': grpc.unary_unary_rpc_method_handler(
                    servicer.ListReleases,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.ListReleasesRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.ListReleasesResponse.SerializeToString,
            ),
            'WatchRelease': grpc.stream_stream_rpc_method_handler(
                    servicer.WatchRelease,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.WatchReleaseRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.WatchReleaseEvent.SerializeToString,
            ),
            'VerifyReleaseDefaults': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyReleaseDefaults,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.VerifyReleaseDefaultsRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.VerifyReleaseDefaultsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kms.v1.ConfigurationReleaseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kms.v1.ConfigurationReleaseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConfigurationReleaseService:
    """---------------------------------------------------------------------------
    ConfigurationReleaseService
    ---------------------------------------------------------------------------

    Configuration releases are immutable namespace-scoped manifests. They
    contain exact parameter/secret version references and non-sensitive
    metadata only; values and secret access tokens are never embedded.
    """

    @staticmethod
    def CreateRelease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.ConfigurationReleaseService/CreateRelease',
            kms_dot_v1_dot_kms__pb2.CreateReleaseRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.CreateReleaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateRelease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.ConfigurationReleaseService/ValidateRelease',
            kms_dot_v1_dot_kms__pb2.ValidateReleaseRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.ValidateReleaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActivateRelease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.ConfigurationReleaseService/ActivateRelease',
            kms_dot_v1_dot_kms__pb2.ActivateReleaseRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.ActivateReleaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRelease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.ConfigurationReleaseService/GetRelease',
            kms_dot_v1_dot_kms__pb2.GetReleaseRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.GetReleaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActiveRelease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.ConfigurationReleaseService/GetActiveRelease',
            kms_dot_v1_dot_kms__pb2.GetActiveReleaseRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.GetActiveReleaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListReleases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.ConfigurationReleaseService/ListReleases',
            kms_dot_v1_dot_kms__pb2.ListReleasesRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.ListReleasesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchRelease(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/kms.v1.ConfigurationReleaseService/WatchRelease',
            kms_dot_v1_dot_kms__pb2.WatchReleaseRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.WatchReleaseEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyReleaseDefaults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.ConfigurationReleaseService/VerifyReleaseDefaults',
            kms_dot_v1_dot_kms__pb2.VerifyReleaseDefaultsRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.VerifyReleaseDefaultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ConfigurationSchemaServiceStub:
    """---------------------------------------------------------------------------
    ConfigurationSchemaService
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSchema = channel.unary_unary(
                '/kms.v1.ConfigurationSchemaService/CreateSchema',
                request_serializer=kms_dot_v1_dot_kms__pb2.CreateSchemaRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.CreateSchemaResponse.FromString,
                _registered_method=True)
        self.GetSchema = channel.unary_unary(
                '/kms.v1.ConfigurationSchemaService/GetSchema',
                request_serializer=kms_dot_v1_dot_kms__pb2.GetSchemaRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.GetSchemaResponse.FromString,
                _registered_method=True)
        self.ListSchemas = channel.unary_unary(
                '/kms.v1.ConfigurationSchemaService/ListSchemas',
                request_serializer=kms_dot_v1_dot_kms__pb2.ListSchemasRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.ListSchemasResponse.FromString,
                _registered_method=True)


class ConfigurationSchemaServiceServicer:
    """---------------------------------------------------------------------------
    ConfigurationSchemaService
    ---------------------------------------------------------------------------

    """

    def CreateSchema(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSchema(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSchemas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConfigurationSchemaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSchema,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.CreateSchemaRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.CreateSchemaResponse.SerializeToString,
            ),
            'GetSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSchema,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.GetSchemaRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.GetSchemaResponse.SerializeToString,
            ),
            'ListSchemas': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSchemas,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.ListSchemasRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.ListSchemasResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kms.v1.ConfigurationSchemaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kms.v1.ConfigurationSchemaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConfigurationSchemaService:
    """---------------------------------------------------------------------------
    ConfigurationSchemaService
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def CreateSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.ConfigurationSchemaService/CreateSchema',
            kms_dot_v1_dot_kms__pb2.CreateSchemaRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.CreateSchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.ConfigurationSchemaService/GetSchema',
            kms_dot_v1_dot_kms__pb2.GetSchemaRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.GetSchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSchemas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.ConfigurationSchemaService/ListSchemas',
            kms_dot_v1_dot_kms__pb2.ListSchemasRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.ListSchemasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AdminServiceStub:
    """---------------------------------------------------------------------------
    AdminService
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateNamespace = channel.unary_unary(
                '/kms.v1.AdminService/CreateNamespace',
                request_serializer=kms_dot_v1_dot_kms__pb2.CreateNamespaceRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.CreateNamespaceResponse.FromString,
                _registered_method=True)
        self.UpdateNamespace = channel.unary_unary(
                '/kms.v1.AdminService/UpdateNamespace',
                request_serializer=kms_dot_v1_dot_kms__pb2.UpdateNamespaceRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.UpdateNamespaceResponse.FromString,
                _registered_method=True)
        self.DeleteNamespace = channel.unary_unary(
                '/kms.v1.AdminService/DeleteNamespace',
                request_serializer=kms_dot_v1_dot_kms__pb2.DeleteNamespaceRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.DeleteNamespaceResponse.FromString,
                _registered_method=True)
        self.ListNamespaces = channel.unary_unary(
                '/kms.v1.AdminService/ListNamespaces',
                request_serializer=kms_dot_v1_dot_kms__pb2.ListNamespacesRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.ListNamespacesResponse.FromString,
                _registered_method=True)
        self.CreatePolicy = channel.unary_unary(
                '/kms.v1.AdminService/CreatePolicy',
                request_serializer=kms_dot_v1_dot_kms__pb2.CreatePolicyRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.CreatePolicyResponse.FromString,
                _registered_method=True)
        self.UpdatePolicy = channel.unary_unary(
                '/kms.v1.AdminService/UpdatePolicy',
                request_serializer=kms_dot_v1_dot_kms__pb2.UpdatePolicyRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.UpdatePolicyResponse.FromString,
                _registered_method=True)
        self.DeletePolicy = channel.unary_unary(
                '/kms.v1.AdminService/DeletePolicy',
                request_serializer=kms_dot_v1_dot_kms__pb2.DeletePolicyRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.DeletePolicyResponse.FromString,
                _registered_method=True)
        self.ListPolicies = channel.unary_unary(
                '/kms.v1.AdminService/ListPolicies',
                request_serializer=kms_dot_v1_dot_kms__pb2.ListPoliciesRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.ListPoliciesResponse.FromString,
                _registered_method=True)
        self.CreateIdentity = channel.unary_unary(
                '/kms.v1.AdminService/CreateIdentity',
                request_serializer=kms_dot_v1_dot_kms__pb2.CreateIdentityRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.CreateIdentityResponse.FromString,
                _registered_method=True)
        self.ListIdentities = channel.unary_unary(
                '/kms.v1.AdminService/ListIdentities',
                request_serializer=kms_dot_v1_dot_kms__pb2.ListIdentitiesRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.ListIdentitiesResponse.FromString,
                _registered_method=True)
        self.RevokeIdentity = channel.unary_unary(
                '/kms.v1.AdminService/RevokeIdentity',
                request_serializer=kms_dot_v1_dot_kms__pb2.RevokeIdentityRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.RevokeIdentityResponse.FromString,
                _registered_method=True)
        self.RotateIdentityToken = channel.unary_unary(
                '/kms.v1.AdminService/RotateIdentityToken',
                request_serializer=kms_dot_v1_dot_kms__pb2.RotateIdentityTokenRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.RotateIdentityTokenResponse.FromString,
                _registered_method=True)
        self.IssueIdentityCertificate = channel.unary_unary(
                '/kms.v1.AdminService/IssueIdentityCertificate',
                request_serializer=kms_dot_v1_dot_kms__pb2.IssueIdentityCertificateRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.IssueIdentityCertificateResponse.FromString,
                _registered_method=True)
        self.RevokeIdentityCertificate = channel.unary_unary(
                '/kms.v1.AdminService/RevokeIdentityCertificate',
                request_serializer=kms_dot_v1_dot_kms__pb2.RevokeIdentityCertificateRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.RevokeIdentityCertificateResponse.FromString,
                _registered_method=True)
        self.WhoAmI = channel.unary_unary(
                '/kms.v1.AdminService/WhoAmI',
                request_serializer=kms_dot_v1_dot_kms__pb2.WhoAmIRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.WhoAmIResponse.FromString,
                _registered_method=True)
        self.GetCACertificate = channel.unary_unary(
                '/kms.v1.AdminService/GetCACertificate',
                request_serializer=kms_dot_v1_dot_kms__pb2.GetCACertificateRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.GetCACertificateResponse.FromString,
                _registered_method=True)
        self.ListAuditEvents = channel.unary_unary(
                '/kms.v1.AdminService/ListAuditEvents',
                request_serializer=kms_dot_v1_dot_kms__pb2.ListAuditEventsRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.ListAuditEventsResponse.FromString,
                _registered_method=True)
        self.ListSubscribers = channel.unary_unary(
                '/kms.v1.AdminService/ListSubscribers',
                request_serializer=kms_dot_v1_dot_kms__pb2.ListSubscribersRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.ListSubscribersResponse.FromString,
                _registered_method=True)
        self.ListReleaseSubscribers = channel.unary_unary(
                '/kms.v1.AdminService/ListReleaseSubscribers',
                request_serializer=kms_dot_v1_dot_kms__pb2.ListReleaseSubscribersRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.ListReleaseSubscribersResponse.FromString,
                _registered_method=True)
        self.ApplyApplicationDefaults = channel.unary_unary(
                '/kms.v1.AdminService/ApplyApplicationDefaults',
                request_serializer=kms_dot_v1_dot_kms__pb2.ApplyApplicationDefaultsRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.ApplyApplicationDefaultsResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/kms.v1.AdminService/Health',
                request_serializer=kms_dot_v1_dot_kms__pb2.HealthRequest.SerializeToString,
                response_deserializer=kms_dot_v1_dot_kms__pb2.HealthResponse.FromString,
                _registered_method=True)


class AdminServiceServicer:
    """---------------------------------------------------------------------------
    AdminService
    ---------------------------------------------------------------------------

    """

    def CreateNamespace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateNamespace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteNamespace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNamespaces(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPolicies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateIdentity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListIdentities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeIdentity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RotateIdentityToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IssueIdentityCertificate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeIdentityCertificate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WhoAmI(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCACertificate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAuditEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSubscribers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListReleaseSubscribers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyApplicationDefaults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateNamespace': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNamespace,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.CreateNamespaceRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.CreateNamespaceResponse.SerializeToString,
            ),
            'UpdateNamespace': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateNamespace,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.UpdateNamespaceRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.UpdateNamespaceResponse.SerializeToString,
            ),
            'DeleteNamespace': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteNamespace,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.DeleteNamespaceRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.DeleteNamespaceResponse.SerializeToString,
            ),
            'ListNamespaces': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNamespaces,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.ListNamespacesRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.ListNamespacesResponse.SerializeToString,
            ),
            'CreatePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePolicy,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.CreatePolicyRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.CreatePolicyResponse.SerializeToString,
            ),
            'UpdatePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePolicy,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.UpdatePolicyRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.UpdatePolicyResponse.SerializeToString,
            ),
            'DeletePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePolicy,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.DeletePolicyRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.DeletePolicyResponse.SerializeToString,
            ),
            'ListPolicies': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPolicies,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.ListPoliciesRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.ListPoliciesResponse.SerializeToString,
            ),
            'CreateIdentity': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateIdentity,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.CreateIdentityRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.CreateIdentityResponse.SerializeToString,
            ),
            'ListIdentities': grpc.unary_unary_rpc_method_handler(
                    servicer.ListIdentities,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.ListIdentitiesRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.ListIdentitiesResponse.SerializeToString,
            ),
            'RevokeIdentity': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeIdentity,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.RevokeIdentityRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.RevokeIdentityResponse.SerializeToString,
            ),
            'RotateIdentityToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RotateIdentityToken,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.RotateIdentityTokenRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.RotateIdentityTokenResponse.SerializeToString,
            ),
            'IssueIdentityCertificate': grpc.unary_unary_rpc_method_handler(
                    servicer.IssueIdentityCertificate,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.IssueIdentityCertificateRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.IssueIdentityCertificateResponse.SerializeToString,
            ),
            'RevokeIdentityCertificate': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeIdentityCertificate,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.RevokeIdentityCertificateRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.RevokeIdentityCertificateResponse.SerializeToString,
            ),
            'WhoAmI': grpc.unary_unary_rpc_method_handler(
                    servicer.WhoAmI,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.WhoAmIRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.WhoAmIResponse.SerializeToString,
            ),
            'GetCACertificate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCACertificate,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.GetCACertificateRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.GetCACertificateResponse.SerializeToString,
            ),
            'ListAuditEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAuditEvents,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.ListAuditEventsRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.ListAuditEventsResponse.SerializeToString,
            ),
            'ListSubscribers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSubscribers,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.ListSubscribersRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.ListSubscribersResponse.SerializeToString,
            ),
            'ListReleaseSubscribers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListReleaseSubscribers,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.ListReleaseSubscribersRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.ListReleaseSubscribersResponse.SerializeToString,
            ),
            'ApplyApplicationDefaults': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyApplicationDefaults,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.ApplyApplicationDefaultsRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.ApplyApplicationDefaultsResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=kms_dot_v1_dot_kms__pb2.HealthRequest.FromString,
                    response_serializer=kms_dot_v1_dot_kms__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kms.v1.AdminService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kms.v1.AdminService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdminService:
    """---------------------------------------------------------------------------
    AdminService
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def CreateNamespace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.AdminService/CreateNamespace',
            kms_dot_v1_dot_kms__pb2.CreateNamespaceRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.CreateNamespaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateNamespace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.AdminService/UpdateNamespace',
            kms_dot_v1_dot_kms__pb2.UpdateNamespaceRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.UpdateNamespaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteNamespace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.AdminService/DeleteNamespace',
            kms_dot_v1_dot_kms__pb2.DeleteNamespaceRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.DeleteNamespaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNamespaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.AdminService/ListNamespaces',
            kms_dot_v1_dot_kms__pb2.ListNamespacesRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.ListNamespacesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.AdminService/CreatePolicy',
            kms_dot_v1_dot_kms__pb2.CreatePolicyRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.CreatePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.AdminService/UpdatePolicy',
            kms_dot_v1_dot_kms__pb2.UpdatePolicyRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.UpdatePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.AdminService/DeletePolicy',
            kms_dot_v1_dot_kms__pb2.DeletePolicyRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.DeletePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPolicies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.AdminService/ListPolicies',
            kms_dot_v1_dot_kms__pb2.ListPoliciesRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.ListPoliciesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateIdentity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.AdminService/CreateIdentity',
            kms_dot_v1_dot_kms__pb2.CreateIdentityRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.CreateIdentityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListIdentities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.AdminService/ListIdentities',
            kms_dot_v1_dot_kms__pb2.ListIdentitiesRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.ListIdentitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeIdentity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.AdminService/RevokeIdentity',
            kms_dot_v1_dot_kms__pb2.RevokeIdentityRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.RevokeIdentityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RotateIdentityToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.AdminService/RotateIdentityToken',
            kms_dot_v1_dot_kms__pb2.RotateIdentityTokenRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.RotateIdentityTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IssueIdentityCertificate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.AdminService/IssueIdentityCertificate',
            kms_dot_v1_dot_kms__pb2.IssueIdentityCertificateRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.IssueIdentityCertificateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeIdentityCertificate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.AdminService/RevokeIdentityCertificate',
            kms_dot_v1_dot_kms__pb2.RevokeIdentityCertificateRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.RevokeIdentityCertificateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WhoAmI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.AdminService/WhoAmI',
            kms_dot_v1_dot_kms__pb2.WhoAmIRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.WhoAmIResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCACertificate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.AdminService/GetCACertificate',
            kms_dot_v1_dot_kms__pb2.GetCACertificateRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.GetCACertificateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAuditEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.AdminService/ListAuditEvents',
            kms_dot_v1_dot_kms__pb2.ListAuditEventsRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.ListAuditEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSubscribers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.AdminService/ListSubscribers',
            kms_dot_v1_dot_kms__pb2.ListSubscribersRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.ListSubscribersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListReleaseSubscribers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.AdminService/ListReleaseSubscribers',
            kms_dot_v1_dot_kms__pb2.ListReleaseSubscribersRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.ListReleaseSubscribersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyApplicationDefaults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.AdminService/ApplyApplicationDefaults',
            kms_dot_v1_dot_kms__pb2.ApplyApplicationDefaultsRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.ApplyApplicationDefaultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v1.AdminService/Health',
            kms_dot_v1_dot_kms__pb2.HealthRequest.SerializeToString,
            kms_dot_v1_dot_kms__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
