import { createHash } from "node:crypto";
import {
  chmod,
  link,
  mkdir,
  mkdtemp,
  readFile,
  stat,
  symlink,
  truncate,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { describe, expect, it } from "vitest";

import { isExecutedEntry, readDescriptor, runCli } from "../src/bin/kms-config-gen-ts.js";
import {
  type ConfigDescriptor,
  DescriptorError,
  generate,
  MAX_RELEASE_ENTRIES,
  parseDescriptor,
  StaleArtifactsError,
  verifyArtifacts,
  writeArtifacts,
} from "../src/configgen/index.js";

const fixtureDirectory = resolve(import.meta.dirname, "fixtures/configgen");
const fixtureBinding = join(fixtureDirectory, "config.generated.ts");
const fixtureSchema = join(fixtureDirectory, "runtime.schema.json");
const fixtureContract = join(fixtureDirectory, "runtime.contract.json");
const fixtureDescriptor = parseDescriptor(
  await readFile(join(fixtureDirectory, "config.kms.json"), "utf8"),
);

function compactJsonText(text: string): string {
  let compact = "";
  let inString = false;
  let escaped = false;
  for (const character of text) {
    if (inString) {
      compact += character;
      if (escaped) escaped = false;
      else if (character === "\\") escaped = true;
      else if (character === '"') inString = false;
    } else if (character === '"') {
      inString = true;
      compact += character;
    } else if (!/\s/u.test(character)) {
      compact += character;
    }
  }
  return compact;
}

describe("TypeScript config generator", () => {
  it("normalizes unordered input and deterministically emits binding, Draft 2020-12 schema and v1 contract", async () => {
    const normalized = parseDescriptor(JSON.stringify(fixtureDescriptor));
    const first = generate(normalized, fixtureImports());
    const second = generate(parseDescriptor(JSON.stringify(fixtureDescriptor)), fixtureImports());

    expect(second).toEqual(first);
    expect(first.binding).toMatch(/^\/\/ Code generated by kms-config-gen-ts; DO NOT EDIT\.\n/u);
    expect(first.binding.endsWith("\n")).toBe(true);
    expect(first.schema.endsWith("\n")).toBe(true);
    expect(first.contract.endsWith("\n")).toBe(true);
    expect(first.schemaSHA256).toBe(
      createHash("sha256").update(compactJsonText(first.schema), "utf8").digest("hex"),
    );

    const schema = JSON.parse(first.schema) as Record<string, unknown>;
    expect(schema.$schema).toBe("https://json-schema.org/draft/2020-12/schema");
    expect(schema).toMatchObject({ type: "object", additionalProperties: false });
    expect(schema.required).toEqual(["database", "runtime"]);
    expect(first.schema).not.toContain("database_password");
    // uint64 bounds must not be rounded through JavaScript number.
    expect(first.schema).toContain("18446744073709551615");

    const contract = JSON.parse(first.contract) as Record<string, unknown>;
    expect(contract).toMatchObject({
      format: "kms-config-contract/v1",
      source: { language: "typescript", module: "./config.js", type: "Config" },
      schema_sha256: first.schemaSHA256,
    });
    expect(first.contract).not.toMatch(/"(?:default|value|physical_path|token)"/iu);
    expect(first.binding).toContain("export class Store");
    expect(first.binding).toContain("encodeDefaultsArtifact as encodeDefaultsArtifactWire");
    expect(first.binding).toContain('from "../../../src/configstore/index.js";');
    expect(first.binding).not.toContain('from "../../../src/configgen/index.js"');
    expect(first.binding).toContain("restartRequiredFields");
    expect(first.binding).toContain("sameSecretIdentity");
    expect(first.binding).toContain("rejectDecode");
    expect(first.binding).toContain("assertRootCoverage<RootConfig");
    expect(first.binding).toContain("exactObject<");
    expect(first.binding).not.toContain("as unknown as ValueCodec");

    await expect(readFile(fixtureBinding, "utf8")).resolves.toBe(first.binding);
    await expect(readFile(fixtureSchema, "utf8")).resolves.toBe(first.schema);
    await expect(readFile(fixtureContract, "utf8")).resolves.toBe(first.contract);
  });

  it("strictly rejects duplicates, unknown properties, unsafe integer representations and alias collisions", () => {
    const duplicate = JSON.stringify(fixtureDescriptor).replace(
      '"format":"kms-config-descriptor/v1"',
      '"format":"kms-config-descriptor/v1","format":"kms-config-descriptor/v1"',
    );
    // JSON.stringify contains spaces with this fixture, so exercise an exact minimal duplicate too.
    expect(() => parseDescriptor('{"format":"x","format":"y"}')).toThrow(
      /duplicate JSON property/u,
    );
    if (duplicate !== JSON.stringify(fixtureDescriptor)) {
      expect(() => parseDescriptor(duplicate)).toThrow(DescriptorError);
    }

    expect(() =>
      generate({
        ...(fixtureDescriptor as ConfigDescriptor),
        unexpected: true,
      }),
    ).toThrow(/unknown property/u);
    expect(() =>
      generate({
        ...fixtureDescriptor,
        secrets: [
          ...fixtureDescriptor.secrets,
          {
            property: "anotherPassword",
            alias: "runtime",
            reload: "hot",
            views: ["worker"],
          },
        ],
      }),
    ).toThrow(/release alias/u);
    expect(() =>
      generate({
        ...fixtureDescriptor,
        groups: [
          {
            alias: "wide",
            fields: [
              {
                property: "epoch",
                jsonName: "epoch",
                reload: "hot",
                views: ["worker"],
                type: { kind: "integer", bits: 64, representation: "number" },
              },
            ],
          },
        ],
        secrets: [],
      }),
    ).toThrow(/require bigint/u);
    expect(() =>
      generate({
        ...fixtureDescriptor,
        source: { module: "/private/build/config.js", type: "Config" },
      }),
    ).toThrow(/not a physical path/u);
    expect(() =>
      generate({
        ...fixtureDescriptor,
        source: { module: "./config.js", type: "class" },
      }),
    ).toThrow(/non-reserved TypeScript identifier/u);
    expect(() =>
      generate(
        {
          format: "kms-config-descriptor/v1",
          source: { module: "./config.js", type: "Config" },
          groups: [
            {
              alias: "runtime",
              fields: [
                {
                  property: "enabled",
                  jsonName: "enabled",
                  reload: "hot",
                  views: ["then"],
                  type: { kind: "boolean" },
                },
              ],
            },
          ],
          secrets: [],
        },
        fixtureImports(),
      ),
    ).toThrow(/then.*collides.*Promise\.then/u);
    expect(() => generate(fixtureDescriptor, { runtimeImport: "/private/runtime.js" })).toThrow(
      /not a physical path/u,
    );
    expect(() =>
      generate({
        format: "kms-config-descriptor/v1",
        source: { module: "./config.js", type: "Config" },
        groups: [
          {
            alias: "runtime",
            fields: [
              {
                property: "enabled",
                jsonName: "enabled",
                reload: "hot",
                views: ["worker"],
                type: { kind: "fixedArray", length: 0, element: { kind: "string" } },
              },
            ],
          },
        ],
        secrets: [],
      }),
    ).toThrow(/length must be from 1 through 1000000/u);
  });

  it("enforces the 256-entry limit before artifact construction", () => {
    const secrets = Array.from({ length: MAX_RELEASE_ENTRIES + 1 }, (_, index) => ({
      property: `Secret${index}`,
      alias: `secret-${index}`,
      reload: "hot",
      views: ["worker"],
    }));
    expect(() =>
      generate({
        format: "kms-config-descriptor/v1",
        source: { module: "./config.js", type: "Config" },
        groups: [],
        secrets,
      }),
    ).toThrow(/maximum is 256/u);
  });

  it("enforces the 256 KiB schema limit and uses locale-independent artifact order", () => {
    const ordered = generate({
      format: "kms-config-descriptor/v1",
      source: { module: "./config.js", type: "Config" },
      groups: ["a_b", "a-b", "A"].map((alias, index) => ({
        alias,
        fields: [
          {
            property: `Field${index}`,
            jsonName: `field-${index}`,
            reload: "hot",
            views: ["worker"],
            type: { kind: "string" },
          },
        ],
      })),
      secrets: [],
    });
    expect((JSON.parse(ordered.schema) as { required: string[] }).required).toEqual([
      "A",
      "a-b",
      "a_b",
    ]);

    const fields = Array.from({ length: 6_000 }, (_, index) => ({
      property: `Field${index}`,
      jsonName: `field-${index}`,
      type: { kind: "string" },
    }));
    expect(() =>
      generate({
        format: "kms-config-descriptor/v1",
        source: { module: "./config.js", type: "Config" },
        groups: [
          {
            alias: "large",
            fields: [
              {
                property: "Large",
                jsonName: "large",
                reload: "hot",
                views: ["worker"],
                type: { kind: "object", fields },
              },
            ],
          },
        ],
        secrets: [],
      }),
    ).toThrow(/maximum is 262144/u);
  });

  it("writes through same-directory temporary files, preserves modes, and leaves matching files untouched", async () => {
    const directory = await mkdtemp(join(tmpdir(), "kms-configgen-files-"));
    const paths = outputPaths(directory);
    const artifacts = generate(fixtureDescriptor, fixtureImports());
    await writeArtifacts(paths, artifacts);
    await chmod(paths.binding, 0o600);
    const before = await stat(paths.binding);
    await writeArtifacts(paths, artifacts);
    const unchanged = await stat(paths.binding);
    expect(unchanged.mtimeMs).toBe(before.mtimeMs);

    const changed = { ...artifacts, binding: `${artifacts.binding}// refreshed\n` };
    await writeArtifacts(paths, changed);
    expect((await stat(paths.binding)).mode & 0o777).toBe(0o600);
    await expect(readFile(paths.binding, "utf8")).resolves.toBe(changed.binding);
    await expect(verifyArtifacts(paths, changed)).resolves.toBeUndefined();
  });

  it("does not replace any artifact when staging a later output fails", async () => {
    const directory = await mkdtemp(join(tmpdir(), "kms-configgen-atomic-"));
    const generated = join(directory, "generated");
    await mkdir(generated);
    const blocker = join(directory, "not-a-directory");
    await writeFile(blocker, "blocker", "utf8");
    const paths = {
      binding: join(generated, "binding.ts"),
      schema: join(generated, "schema.json"),
      contract: join(blocker, "contract.json"),
    };
    await writeFile(paths.binding, "old binding", "utf8");
    await writeFile(paths.schema, "old schema", "utf8");

    await expect(
      writeArtifacts(paths, generate(fixtureDescriptor, fixtureImports())),
    ).rejects.toThrow(/configgen/u);
    await expect(readFile(paths.binding, "utf8")).resolves.toBe("old binding");
    await expect(readFile(paths.schema, "utf8")).resolves.toBe("old schema");
  });

  it("rejects output aliases through symlinked parents and hardlinks", async () => {
    const directory = await mkdtemp(join(tmpdir(), "kms-configgen-identities-"));
    const canonicalParent = join(directory, "canonical");
    const linkedParent = join(directory, "linked");
    await mkdir(canonicalParent);
    await symlink(canonicalParent, linkedParent, "dir");
    const artifacts = generate(fixtureDescriptor, fixtureImports());

    await expect(
      writeArtifacts(
        {
          binding: join(canonicalParent, "same-output"),
          schema: join(linkedParent, "same-output"),
          contract: join(directory, "contract.json"),
        },
        artifacts,
      ),
    ).rejects.toThrow(/same filesystem object/u);
    await expect(stat(join(canonicalParent, "same-output"))).rejects.toMatchObject({
      code: "ENOENT",
    });

    const firstLink = join(directory, "first-link");
    const secondLink = join(directory, "second-link");
    await writeFile(firstLink, "existing", "utf8");
    await link(firstLink, secondLink);
    await expect(
      verifyArtifacts(
        { binding: firstLink, schema: secondLink, contract: join(directory, "other") },
        artifacts,
      ),
    ).rejects.toThrow(/same filesystem object/u);
  });

  it("rejects missing output case aliases on case-insensitive filesystems", async () => {
    const directory = await mkdtemp(join(tmpdir(), "kms-configgen-case-"));
    const canonicalParent = join(directory, "CaseSensitiveProbe");
    const caseAliasParent = join(directory, "casesensitiveprobe");
    await mkdir(canonicalParent);
    try {
      await stat(caseAliasParent);
    } catch {
      // The host filesystem is case-sensitive, so these are distinct entries.
      return;
    }
    await expect(
      writeArtifacts(
        {
          binding: join(canonicalParent, "Result.TS"),
          schema: join(caseAliasParent, "result.ts"),
          contract: join(directory, "contract.json"),
        },
        generate(fixtureDescriptor, fixtureImports()),
      ),
    ).rejects.toThrow(/same filesystem object/u);
  });

  it("refuses to overwrite a descriptor through a filesystem alias", async () => {
    const directory = await mkdtemp(join(tmpdir(), "kms-configgen-descriptor-alias-"));
    const descriptorTarget = join(directory, "descriptor-target.json");
    const descriptorAlias = join(directory, "descriptor-alias.json");
    const document = JSON.stringify(fixtureDescriptor);
    await writeFile(descriptorTarget, document, "utf8");
    await symlink(descriptorTarget, descriptorAlias);
    const paths = {
      binding: descriptorTarget,
      schema: join(directory, "schema.json"),
      contract: join(directory, "contract.json"),
    };
    const stderr: string[] = [];
    const code = await runCli(cliArgs(descriptorAlias, paths, fixtureImportArgs()), {
      stdout: () => undefined,
      stderr: (message) => stderr.push(message),
    });

    expect(code).toBe(1);
    expect(stderr.join(" ")).toMatch(/descriptor.*binding output.*same filesystem object/u);
    await expect(readFile(descriptorTarget, "utf8")).resolves.toBe(document);
    await expect(stat(paths.schema)).rejects.toMatchObject({ code: "ENOENT" });
  });

  it("rejects an oversized sparse descriptor from metadata before reading its contents", async () => {
    const directory = await mkdtemp(join(tmpdir(), "kms-configgen-descriptor-size-"));
    const descriptorPath = join(directory, "huge.kms.json");
    const paths = outputPaths(directory);
    await writeFile(descriptorPath, "{}", "utf8");
    // A logical size beyond Node's ordinary readFile ceiling proves that the
    // CLI applies its own 1 MiB preflight rather than attempting an unbounded
    // allocation. truncate creates a sparse file on CI filesystems.
    await truncate(descriptorPath, 3 * 1024 * 1024 * 1024);
    const stderr: string[] = [];

    const code = await runCli(cliArgs(descriptorPath, paths, fixtureImportArgs()), {
      stdout: () => undefined,
      stderr: (message) => stderr.push(message),
    });

    expect(code).toBe(1);
    expect(stderr.join(" ")).toMatch(/descriptor is 3221225472 bytes; maximum is 1048576 bytes/u);
    await expect(stat(paths.binding)).rejects.toMatchObject({ code: "ENOENT" });
    await expect(stat(paths.schema)).rejects.toMatchObject({ code: "ENOENT" });
    await expect(stat(paths.contract)).rejects.toMatchObject({ code: "ENOENT" });
  });

  it("rejects invalid UTF-8 descriptors without generating any outputs", async () => {
    const directory = await mkdtemp(join(tmpdir(), "kms-configgen-descriptor-utf8-"));
    const descriptorPath = join(directory, "invalid-utf8.kms.json");
    const paths = outputPaths(directory);
    const document = Buffer.from(JSON.stringify(fixtureDescriptor), "utf8");
    const moduleMarker = Buffer.from('"module":"', "utf8");
    const moduleStart = document.indexOf(moduleMarker);
    expect(moduleStart).toBeGreaterThanOrEqual(0);
    const insertion = moduleStart + moduleMarker.byteLength;
    await writeFile(
      descriptorPath,
      Buffer.concat([
        document.subarray(0, insertion),
        Buffer.from([0xc3, 0x28]),
        document.subarray(insertion),
      ]),
    );

    await expect(readDescriptor(descriptorPath)).rejects.toThrow(
      "configgen: descriptor is not valid UTF-8",
    );
    const stderr: string[] = [];
    const code = await runCli(cliArgs(descriptorPath, paths, fixtureImportArgs()), {
      stdout: () => undefined,
      stderr: (message) => stderr.push(message),
    });

    expect(code).toBe(1);
    expect(stderr).toEqual(["configgen: descriptor is not valid UTF-8\n"]);
    await expect(stat(paths.binding)).rejects.toMatchObject({ code: "ENOENT" });
    await expect(stat(paths.schema)).rejects.toMatchObject({ code: "ENOENT" });
    await expect(stat(paths.contract)).rejects.toMatchObject({ code: "ENOENT" });
  });

  it.runIf(process.platform === "linux")(
    "bounded descriptor reads support virtual files whose reported size is zero",
    async () => {
      const path = "/proc/self/status";
      expect((await stat(path)).size).toBe(0);
      await expect(readDescriptor(path)).resolves.toContain("Name:");
    },
  );

  it("recognizes a symlinked executable entry", async () => {
    const directory = await mkdtemp(join(tmpdir(), "kms-configgen-entry-"));
    const target = resolve(import.meta.dirname, "../src/bin/kms-config-gen-ts.ts");
    const entry = join(directory, "kms-config-gen-ts");
    await symlink(target, entry);
    await expect(isExecutedEntry(entry)).resolves.toBe(true);
  });

  it("check mode reports all stale paths with a nonzero exit and never rewrites them", async () => {
    const directory = await mkdtemp(join(tmpdir(), "kms-configgen-check-"));
    const descriptorPath = join(directory, "config.kms.json");
    const paths = outputPaths(directory);
    await mkdir(join(directory, "generated"), { recursive: true });
    await writeFile(descriptorPath, JSON.stringify(fixtureDescriptor), "utf8");
    await writeFile(paths.binding, "stale binding", "utf8");
    await writeFile(paths.schema, "stale schema", "utf8");
    await writeFile(paths.contract, "stale contract", "utf8");
    const stderr: string[] = [];
    const code = await runCli(cliArgs(descriptorPath, paths, ["--check", ...fixtureImportArgs()]), {
      stdout: () => undefined,
      stderr: (message) => stderr.push(message),
    });
    expect(code).toBe(1);
    expect(stderr.join(" ")).toContain("stale");
    expect(await readFile(paths.binding, "utf8")).toBe("stale binding");
    expect(await readFile(paths.schema, "utf8")).toBe("stale schema");
    expect(await readFile(paths.contract, "utf8")).toBe("stale contract");
    await expect(
      verifyArtifacts(paths, generate(fixtureDescriptor, fixtureImports())),
    ).rejects.toBeInstanceOf(StaleArtifactsError);
  });

  it("check mode identifies the exact member of a mixed artifact set", async () => {
    const directory = await mkdtemp(join(tmpdir(), "kms-configgen-mixed-"));
    const paths = outputPaths(directory);
    const artifacts = generate(fixtureDescriptor, fixtureImports());
    await writeArtifacts(paths, artifacts);
    await writeFile(paths.schema, `${artifacts.schema}stale\n`, "utf8");

    try {
      await verifyArtifacts(paths, artifacts);
      throw new Error("expected mixed artifact verification to fail");
    } catch (error) {
      expect(error).toBeInstanceOf(StaleArtifactsError);
      expect((error as StaleArtifactsError).paths).toEqual([paths.schema]);
    }
  });

  it("CLI accepts traversal-resolving explicit paths without interpreting descriptor data as paths", async () => {
    const parent = await mkdtemp(join(tmpdir(), "kms-configgen-cli-"));
    const working = join(parent, "nested");
    const descriptorPath = join(parent, "descriptor.json");
    await writeFile(descriptorPath, JSON.stringify(fixtureDescriptor), "utf8");
    const paths = {
      binding: join(working, "..", "binding.ts"),
      schema: join(working, "..", "schema.json"),
      contract: join(working, "..", "contract.json"),
    };
    const stderr: string[] = [];
    const code = await runCli(cliArgs(descriptorPath, paths, fixtureImportArgs()), {
      stdout: () => undefined,
      stderr: (message) => stderr.push(message),
    });
    expect(code, stderr.join(" ")).toBe(0);
    expect(await readFile(join(parent, "binding.ts"), "utf8")).toContain("export class Store");
    expect(await readFile(join(parent, "schema.json"), "utf8")).toContain("draft/2020-12");
  });
});

function fixtureImports(): {
  runtimeImport: string;
  coreImport: string;
} {
  return {
    runtimeImport: "../../../src/configstore/index.js",
    coreImport: "../../../src/index.js",
  };
}

function fixtureImportArgs(): string[] {
  return [
    "--runtime-import",
    "../../../src/configstore/index.js",
    "--core-import",
    "../../../src/index.js",
  ];
}

function outputPaths(directory: string): { binding: string; schema: string; contract: string } {
  return {
    binding: join(directory, "generated/config.generated.ts"),
    schema: join(directory, "generated/runtime.schema.json"),
    contract: join(directory, "generated/runtime.contract.json"),
  };
}

function cliArgs(
  descriptor: string,
  paths: { binding: string; schema: string; contract: string },
  extra: readonly string[],
): string[] {
  return [
    "--descriptor",
    descriptor,
    "--binding-output",
    paths.binding,
    "--schema-output",
    paths.schema,
    "--contract-output",
    paths.contract,
    ...extra,
  ];
}
