// Code generated by kms-config-gen; DO NOT EDIT.

package mutatinggenerated

import (
	context "context"
	json "encoding/json"
	errors "errors"
	fmt "fmt"
	rootconfig "github.com/Suhaibinator/kms/internal/configgen/testdata/mutating"
	configstore "github.com/Suhaibinator/kms/sdk/go/configstore"
	kmsclient "github.com/Suhaibinator/kms/sdk/go/kmsclient"
	atomic "sync/atomic"
	time "time"
)

const generatedSchemaSHA256 = "95e30071e4dfde584cdb41e43d8659ab36523b8dee1ae8ad3b5614eeca36a850"

var generatedContract = []configstore.ContractEntry{
	{Alias: "runtime", Kind: configstore.ContractKindParameter, ContentType: "json"},
	{Alias: "token", Kind: configstore.ContractKindSecret, ContentType: ""},
}

// Options configures the generated managed configuration store.
type Options struct {
	Release              string
	Defaults             func() *rootconfig.Config
	AllowDefaultMismatch bool
	OnDefaultMismatch    func(configstore.DefaultMismatchReport)
	OnCandidateRejected  func(configstore.CandidateRejectionReport)
	SecretTokenProvider  kmsclient.SecretTokenProvider
	ReconcileInterval    time.Duration
	MaxConcurrentFetches int
	InstanceID           string
}

// Store publishes whole immutable configuration generations.
type Store struct {
	active   atomic.Pointer[immutableGeneration]
	manager  *configstore.Manager
	defaults *rootconfig.Config
}

type immutableGeneration struct {
	config  *rootconfig.Config
	release configstore.ReleaseIdentity
}

// Snapshot captures exactly one immutable generation.
type Snapshot struct{ generation *immutableGeneration }

// WorkerView is an immutable projection captured from a Snapshot.
type WorkerView struct{ generation *immutableGeneration }

// EncodeParameterGroups encodes every complete non-secret parameter group from root.
// The returned documents use the same canonical encodings accepted by the generated store.
func EncodeParameterGroups(root *rootconfig.Config) (map[string]json.RawMessage, error) {
	if err := validateInlinePointers(root); err != nil {
		return nil, err
	}
	groups := make(map[string]json.RawMessage, 1)
	group0, err := configstore.EncodeGroup(root, groupFields0)
	if err != nil {
		return nil, fmt.Errorf("generated config store: encode parameter group runtime: %w", err)
	}
	groups["runtime"] = group0
	return groups, nil
}

// EncodeDefaultsArtifact encodes a complete parameter-only defaults artifact for profile.
// Secret contract metadata is included, but secret values are structurally excluded.
func EncodeDefaultsArtifact(profile string, root *rootconfig.Config) ([]byte, error) {
	groups, err := EncodeParameterGroups(root)
	if err != nil {
		return nil, err
	}
	parameters := make([]configstore.DefaultsParameter, 0, len(groups))
	for _, entry := range generatedContract {
		if entry.Kind != configstore.ContractKindParameter {
			continue
		}
		value, ok := groups[entry.Alias]
		if !ok {
			return nil, fmt.Errorf("generated config store: missing encoded parameter group %s", entry.Alias)
		}
		parameters = append(parameters, configstore.DefaultsParameter{Alias: entry.Alias, ContentType: entry.ContentType, Value: string(value)})
	}
	return configstore.EncodeDefaultsArtifact(configstore.DefaultsArtifact{
		Format:       configstore.DefaultsArtifactFormat,
		Profile:      profile,
		SchemaSHA256: generatedSchemaSHA256,
		Contract:     generatedContract,
		Parameters:   parameters,
	})
}

// Start synchronously validates and publishes the initial release, then watches in the background.
func Start(ctx context.Context, client *kmsclient.Client, options Options) (*Store, error) {
	if options.Defaults == nil {
		return nil, errors.New("generated config store: Options.Defaults is required")
	}
	defaults := options.Defaults()
	if defaults == nil {
		return nil, errors.New("generated config store: Options.Defaults returned nil")
	}
	if err := validateInlinePointers(defaults); err != nil {
		return nil, err
	}
	if !defaults.Token.IsZero() || defaults.Token.Path() != "" || defaults.Token.Version() != 0 || defaults.Token.ContentType() != "" {
		return nil, fmt.Errorf("generated config store: default secret Token must be zero")
	}
	store := &Store{defaults: cloneRoot(defaults)}
	manager, err := configstore.Start(ctx, client, configstore.Options{
		Release:              options.Release,
		Contract:             generatedContract,
		AllowDefaultMismatch: options.AllowDefaultMismatch,
		OnDefaultMismatch:    options.OnDefaultMismatch,
		OnCandidateRejected:  options.OnCandidateRejected,
		SecretTokenProvider:  options.SecretTokenProvider,
		ReconcileInterval:    options.ReconcileInterval,
		MaxConcurrentFetches: options.MaxConcurrentFetches,
		InstanceID:           options.InstanceID,
	}, store.prepare)
	if err != nil {
		return nil, err
	}
	store.manager = manager
	return store, nil
}

func (s *Store) Status() configstore.Status { return s.manager.Status() }
func (s *Store) Stats() configstore.Stats   { return s.manager.Stats() }
func (s *Store) Wait() error                { return s.manager.Wait() }

func (s *Store) prepare(ctx context.Context, snapshot kmsclient.ReleaseSnapshot) (configstore.PreparedCandidate, error) {
	if err := ctx.Err(); err != nil {
		return configstore.PreparedCandidate{}, err
	}
	candidate := cloneRoot(s.defaults)
	parameter0, ok := snapshot.Parameter("runtime")
	if !ok {
		return configstore.PreparedCandidate{}, configstore.Reject(configstore.RejectConfigContractMismatch, fmt.Errorf("missing parameter group runtime"))
	}
	if err := configstore.DecodeGroup(parameter0.Value(), candidate, groupFields0); err != nil {
		return configstore.PreparedCandidate{}, configstore.RejectDecode("runtime", err)
	}
	secret0, ok := snapshot.Secret("token")
	if !ok {
		return configstore.PreparedCandidate{}, configstore.Reject(configstore.RejectConfigContractMismatch, fmt.Errorf("missing secret alias token"))
	}
	candidate.Token = secret0.Clone()
	if err := candidate.Validate(); err != nil {
		return configstore.PreparedCandidate{}, configstore.Reject(configstore.RejectConfigValidationFailed, fmt.Errorf("validate KMS configuration: %w", err))
	}
	if err := validateInlinePointers(candidate); err != nil {
		return configstore.PreparedCandidate{}, configstore.Reject(configstore.RejectConfigValidationFailed, err)
	}
	effectiveDefaults := cloneRoot(s.defaults)
	effectiveDefaults.Token = secret0.Clone()
	if err := effectiveDefaults.Validate(); err != nil {
		return configstore.PreparedCandidate{}, configstore.Reject(configstore.RejectConfigValidationFailed, fmt.Errorf("validate effective application defaults: %w", err))
	}
	if err := validateInlinePointers(effectiveDefaults); err != nil {
		return configstore.PreparedCandidate{}, configstore.Reject(configstore.RejectConfigValidationFailed, err)
	}
	// Validation is application code and may mutate its receiver. Clone once more before retaining either value.
	candidate = cloneRoot(candidate)
	effectiveDefaults = cloneRoot(effectiveDefaults)
	differences := make([]configstore.FieldDifference, 0)
	if !equalValue0(effectiveDefaults.Name, candidate.Name) {
		differences = append(differences, configstore.FieldDifference{Path: "runtime.name", Expected: reportValue0(effectiveDefaults.Name), Actual: reportValue0(candidate.Name)})
	}
	restartRequired := make([]string, 0)
	active := s.active.Load()
	if active != nil {
	}
	generation := &immutableGeneration{config: candidate, release: configstore.ReleaseIdentityFromSnapshot(snapshot)}
	return configstore.PreparedCandidate{
		Publish:               func() { s.active.Store(generation) },
		Abort:                 func() {},
		DefaultDifferences:    differences,
		RestartRequiredFields: restartRequired,
	}, nil
}

var groupFields0 = []configstore.FieldCodec{
	{JSONName: "name", FieldIndex: []int{0}, Value: configstore.ValueCodec{Kind: configstore.CodecString}},
}

// Current performs exactly one atomic load and captures that generation.
func (s *Store) Current() Snapshot {
	generation := s.active.Load()
	return Snapshot{generation: generation}
}

func (s Snapshot) Release() configstore.ReleaseIdentity { return s.generation.release }

// Config returns a defensive copy of this complete immutable generation.
// Use generated views instead when reading hot configuration in an operation path.
func (s Snapshot) Config() *rootconfig.Config { return cloneRoot(s.generation.config) }

func (s Snapshot) Worker() WorkerView { return WorkerView{generation: s.generation} }

func (v WorkerView) Name() string            { return v.generation.config.Name }
func (v WorkerView) Token() kmsclient.Secret { return v.generation.config.Token.Clone() }

func cloneRoot(value *rootconfig.Config) *rootconfig.Config {
	if value == nil {
		return nil
	}
	// Root cloning is preparation-only. It also isolates excluded fields that generated getters never expose.
	out := configstore.Clone(*value)
	out.Token = value.Token.Clone()
	return &out
}

func validateInlinePointers(value *rootconfig.Config) error {
	if value == nil {
		return errors.New("generated config store: configuration root is nil")
	}
	return nil
}

func cloneValue0(value string) string {
	return value
}

func equalValue0(left, right string) bool {
	return left == right
}

func reportValue0(value string) any {
	return value
}
