"""Generated by kms-config-gen-py; DO NOT EDIT."""
from __future__ import annotations

from typing import Any, Mapping, cast

import tests.fixtures.configgen.source as _source
from kms_paramstore import Secret
from kms_paramstore.configstore import ConfigBinding, ConfigView

ApplicationConfig = _source.ApplicationConfig

SCHEMA_SHA256 = "2751c2f83659dcde5450bf7608f1aa6229e191db7ceaa58c3b430742c7fed6ee"
CONTRACT = (('db_password', 'secret', ''), ('runtime', 'parameter', 'json'))

class ServerConfigView(ConfigView):
    @property
    def debug(self) -> bool:
        return cast(bool, ConfigView.get(self, 'debug'))

    @property
    def password(self) -> Secret:
        return cast(Secret, ConfigView.get(self, 'password'))

    @property
    def port(self) -> int:
        return cast(int, ConfigView.get(self, 'port'))

class GeneratedConfigStore(ConfigBinding[ApplicationConfig]):
    def __init__(self, defaults: Mapping[str, Any] | ApplicationConfig) -> None:
        super().__init__(ApplicationConfig, defaults)

    def server(self) -> ServerConfigView:
        return ServerConfigView(self.current, ('debug', 'password', 'port'))
