package configgen

import (
	"fmt"
	"go/format"
	"go/types"
	"sort"
	"strconv"
	"strings"
)

type bindingRenderer struct {
	model          *ir
	packageName    string
	contract       renderedContract
	body           strings.Builder
	imports        map[string]string
	usedAliases    map[string]bool
	helpers        []*typeIR
	helperByType   map[types.Type]int
	rootTypeString string
}

func renderBinding(model *ir, packageName string, contract renderedContract) ([]byte, error) {
	r := &bindingRenderer{
		model:        model,
		packageName:  packageName,
		contract:     contract,
		imports:      make(map[string]string),
		usedAliases:  make(map[string]bool),
		helperByType: make(map[types.Type]int),
	}
	for _, imported := range []struct{ path, alias string }{
		{"context", "context"}, {"errors", "errors"}, {"fmt", "fmt"}, {"sync/atomic", "atomic"}, {"time", "time"},
		{configstorePath, "configstore"}, {paramstorePath, "paramstore"},
	} {
		r.addImport(imported.path, imported.alias)
	}
	rootAlias := r.addImport(model.PackagePath, "rootconfig")
	r.rootTypeString = rootAlias + "." + model.TypeName
	for _, field := range model.Fields {
		if !field.Secret {
			r.addHelper(field.Type)
		}
	}
	r.renderBody()

	var source strings.Builder
	source.WriteString("// Code generated by kms-config-gen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&source, "package %s\n\n", packageName)
	source.WriteString("import (\n")
	paths := make([]string, 0, len(r.imports))
	for path := range r.imports {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	for _, path := range paths {
		fmt.Fprintf(&source, "\t%s %s\n", r.imports[path], strconv.Quote(path))
	}
	source.WriteString(")\n\n")
	source.WriteString(r.body.String())
	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return nil, fmt.Errorf("configgen: gofmt generated binding: %w", err)
	}
	return formatted, nil
}

func (r *bindingRenderer) addImport(path, preferred string) string {
	if alias, ok := r.imports[path]; ok {
		return alias
	}
	alias := sanitizeIdentifier(preferred)
	if alias == "" {
		alias = "pkg"
	}
	base := alias
	for suffix := 2; r.usedAliases[alias]; suffix++ {
		alias = base + strconv.Itoa(suffix)
	}
	r.imports[path] = alias
	r.usedAliases[alias] = true
	return alias
}

func sanitizeIdentifier(value string) string {
	var b strings.Builder
	for i, char := range value {
		if (char >= 'a' && char <= 'z') || (char >= 'A' && char <= 'Z') || char == '_' || (i > 0 && char >= '0' && char <= '9') {
			b.WriteRune(char)
		}
	}
	return b.String()
}

func (r *bindingRenderer) typeString(t types.Type) string {
	return types.TypeString(t, func(pkg *types.Package) string {
		if pkg == nil {
			return ""
		}
		if alias, ok := r.imports[pkg.Path()]; ok {
			return alias
		}
		return r.addImport(pkg.Path(), pkg.Name())
	})
}

func (r *bindingRenderer) line(format string, args ...any) {
	if len(args) == 0 {
		r.body.WriteString(format)
	} else {
		fmt.Fprintf(&r.body, format, args...)
	}
	r.body.WriteByte('\n')
}

func (r *bindingRenderer) renderBody() {
	r.renderContract()
	r.renderTypes()
	r.renderStart()
	r.renderPrepare()
	r.renderGroupCodecs()
	r.renderSnapshots()
	r.renderCloneRoot()
	r.renderHelpers()
}

func (r *bindingRenderer) renderContract() {
	r.line("const generatedSchemaSHA256 = %s", strconv.Quote(r.contract.SchemaSHA256))
	r.line("")
	r.line("var generatedContract = []configstore.ContractEntry{")
	for _, entry := range r.contract.Entries {
		kind := "configstore.ContractKindParameter"
		if entry.Kind == "secret" {
			kind = "configstore.ContractKindSecret"
		}
		r.line("\t{Alias: %s, Kind: %s, ContentType: %s},", strconv.Quote(entry.Alias), kind, strconv.Quote(entry.ContentType))
	}
	r.line("}")
	r.line("")
}

func (r *bindingRenderer) renderTypes() {
	r.line("// Options configures the generated managed configuration store.")
	r.line("type Options struct {")
	r.line("\tRelease string")
	r.line("\tDefaults func() *%s", r.rootTypeString)
	r.line("\tAllowDefaultMismatch bool")
	r.line("\tOnDefaultMismatch func(configstore.DefaultMismatchReport)")
	r.line("\tOnCandidateRejected func(configstore.CandidateRejectionReport)")
	r.line("\tSecretTokenProvider paramstore.SecretTokenProvider")
	r.line("\tReconcileInterval time.Duration")
	r.line("\tMaxConcurrentFetches int")
	r.line("\tInstanceID string")
	r.line("}")
	r.line("")
	r.line("// Store publishes whole immutable configuration generations.")
	r.line("type Store struct {")
	r.line("\tactive atomic.Pointer[immutableGeneration]")
	r.line("\tmanager *configstore.Manager")
	r.line("\tdefaults *%s", r.rootTypeString)
	r.line("}")
	r.line("")
	r.line("type immutableGeneration struct {")
	r.line("\tconfig *%s", r.rootTypeString)
	r.line("\trelease configstore.ReleaseIdentity")
	r.line("}")
	r.line("")
	r.line("// Snapshot captures exactly one immutable generation.")
	r.line("type Snapshot struct { generation *immutableGeneration }")
	r.line("")
	for _, view := range r.model.Views {
		r.line("// %sView is an immutable projection captured from a Snapshot.", view.Method)
		r.line("type %sView struct { generation *immutableGeneration }", view.Method)
		r.line("")
	}
}

func (r *bindingRenderer) renderStart() {
	r.line("// Start synchronously validates and publishes the initial release, then watches in the background.")
	r.line("func Start(ctx context.Context, client *paramstore.Client, options Options) (*Store, error) {")
	r.line("\tif options.Defaults == nil {")
	r.line("\t\treturn nil, errors.New(%s)", strconv.Quote("generated config store: Options.Defaults is required"))
	r.line("\t}")
	r.line("\tdefaults := options.Defaults()")
	r.line("\tif defaults == nil {")
	r.line("\t\treturn nil, errors.New(%s)", strconv.Quote("generated config store: Options.Defaults returned nil"))
	r.line("\t}")
	for _, field := range r.model.Secrets {
		r.line("\tif !defaults.%s.IsZero() || defaults.%s.Path() != \"\" || defaults.%s.Version() != 0 || defaults.%s.ContentType() != \"\" {", field.GoName, field.GoName, field.GoName, field.GoName)
		r.line("\t\treturn nil, fmt.Errorf(%s)", strconv.Quote("generated config store: default secret "+field.GoName+" must be zero"))
		r.line("\t}")
	}
	r.line("\tstore := &Store{defaults: cloneRoot(defaults)}")
	r.line("\tmanager, err := configstore.Start(ctx, client, configstore.Options{")
	r.line("\t\tRelease: options.Release,")
	r.line("\t\tContract: generatedContract,")
	r.line("\t\tAllowDefaultMismatch: options.AllowDefaultMismatch,")
	r.line("\t\tOnDefaultMismatch: options.OnDefaultMismatch,")
	r.line("\t\tOnCandidateRejected: options.OnCandidateRejected,")
	r.line("\t\tSecretTokenProvider: options.SecretTokenProvider,")
	r.line("\t\tReconcileInterval: options.ReconcileInterval,")
	r.line("\t\tMaxConcurrentFetches: options.MaxConcurrentFetches,")
	r.line("\t\tInstanceID: options.InstanceID,")
	r.line("\t}, store.prepare)")
	r.line("\tif err != nil {")
	r.line("\t\treturn nil, err")
	r.line("\t}")
	r.line("\tstore.manager = manager")
	r.line("\treturn store, nil")
	r.line("}")
	r.line("")
	r.line("func (s *Store) Status() configstore.Status { return s.manager.Status() }")
	r.line("func (s *Store) Stats() configstore.Stats { return s.manager.Stats() }")
	r.line("func (s *Store) Wait() error { return s.manager.Wait() }")
	r.line("")
}

func (r *bindingRenderer) renderPrepare() {
	r.line("func (s *Store) prepare(ctx context.Context, snapshot paramstore.ReleaseSnapshot) (configstore.PreparedCandidate, error) {")
	r.line("\tif err := ctx.Err(); err != nil { return configstore.PreparedCandidate{}, err }")
	r.line("\tcandidate := cloneRoot(s.defaults)")
	for groupIndex, group := range r.model.Groups {
		r.line("\tparameter%d, ok := snapshot.Parameter(%s)", groupIndex, strconv.Quote(group.Alias))
		r.line("\tif !ok {")
		r.line("\t\treturn configstore.PreparedCandidate{}, configstore.Reject(configstore.RejectConfigContractMismatch, fmt.Errorf(%s))", strconv.Quote("missing parameter group "+group.Alias))
		r.line("\t}")
		r.line("\tif err := configstore.DecodeGroup(parameter%d.Value(), candidate, groupFields%d); err != nil {", groupIndex, groupIndex)
		r.line("\t\treturn configstore.PreparedCandidate{}, configstore.RejectDecode(%s, err)", strconv.Quote(group.Alias))
		r.line("\t}")
	}
	for secretIndex, field := range r.model.Secrets {
		r.line("\tsecret%d, ok := snapshot.Secret(%s)", secretIndex, strconv.Quote(field.Source))
		r.line("\tif !ok {")
		r.line("\t\treturn configstore.PreparedCandidate{}, configstore.Reject(configstore.RejectConfigContractMismatch, fmt.Errorf(%s))", strconv.Quote("missing secret alias "+field.Source))
		r.line("\t}")
		r.line("\tcandidate.%s = secret%d.Clone()", field.GoName, secretIndex)
	}
	r.line("\tif err := candidate.Validate(); err != nil {")
	r.line("\t\treturn configstore.PreparedCandidate{}, configstore.Reject(configstore.RejectConfigValidationFailed, fmt.Errorf(%s, err))", strconv.Quote("validate KMS configuration: %w"))
	r.line("\t}")
	r.line("\teffectiveDefaults := cloneRoot(s.defaults)")
	for _, field := range r.model.Secrets {
		r.line("\teffectiveDefaults.%s = candidate.%s.Clone()", field.GoName, field.GoName)
	}
	r.line("\tif err := effectiveDefaults.Validate(); err != nil {")
	r.line("\t\treturn configstore.PreparedCandidate{}, configstore.Reject(configstore.RejectConfigValidationFailed, fmt.Errorf(%s, err))", strconv.Quote("validate effective application defaults: %w"))
	r.line("\t}")
	r.line("\t// Validation is application code and may mutate its receiver. Clone once more before retaining either value.")
	r.line("\tcandidate = cloneRoot(candidate)")
	r.line("\teffectiveDefaults = cloneRoot(effectiveDefaults)")
	r.line("\tdifferences := make([]configstore.FieldDifference, 0)")
	for _, field := range r.model.Fields {
		if field.Secret {
			continue
		}
		h := r.helperByType[field.Type.GoType]
		r.line("\tif !equalValue%d(s.defaults.%s, candidate.%s) {", h, field.GoName, field.GoName)
		r.line("\t\tdifferences = append(differences, configstore.FieldDifference{Path: %s, Expected: reportValue%d(s.defaults.%s), Actual: reportValue%d(candidate.%s)})", strconv.Quote(field.canonicalName()), h, field.GoName, h, field.GoName)
		r.line("\t}")
	}
	r.line("\trestartRequired := make([]string, 0)")
	r.line("\tactive := s.active.Load()")
	r.line("\tif active != nil {")
	for _, field := range r.model.Fields {
		if field.Reload != "restart" {
			continue
		}
		if field.Secret {
			r.line("\t\tif candidate.%s.Path() != active.config.%s.Path() || candidate.%s.Version() != active.config.%s.Version() {", field.GoName, field.GoName, field.GoName, field.GoName)
		} else {
			h := r.helperByType[field.Type.GoType]
			r.line("\t\tif !equalValue%d(candidate.%s, active.config.%s) {", h, field.GoName, field.GoName)
		}
		r.line("\t\t\trestartRequired = append(restartRequired, %s)", strconv.Quote(field.canonicalName()))
		r.line("\t\t}")
	}
	r.line("\t}")
	r.line("\tgeneration := &immutableGeneration{config: candidate, release: configstore.ReleaseIdentityFromSnapshot(snapshot)}")
	r.line("\treturn configstore.PreparedCandidate{")
	r.line("\t\tPublish: func() { s.active.Store(generation) },")
	r.line("\t\tAbort: func() {},")
	r.line("\t\tDefaultDifferences: differences,")
	r.line("\t\tRestartRequiredFields: restartRequired,")
	r.line("\t}, nil")
	r.line("}")
	r.line("")
}

func (r *bindingRenderer) renderGroupCodecs() {
	for groupIndex, group := range r.model.Groups {
		r.line("var groupFields%d = []configstore.FieldCodec{", groupIndex)
		for _, field := range group.Fields {
			r.line("\t{JSONName: %s, FieldIndex: []int{%d}, Value: %s},", strconv.Quote(field.JSONName), field.Index, r.codecLiteral(field.Type, "\t"))
		}
		r.line("}")
		r.line("")
	}
}

func (r *bindingRenderer) codecLiteral(value *typeIR, indent string) string {
	kind := map[typeKind]string{
		typeBool: "CodecBool", typeString: "CodecString", typeInt: "CodecInt", typeUint: "CodecUint",
		typeFloat: "CodecFloat", typeDuration: "CodecDuration", typePointer: "CodecPointer", typeBytes: "CodecBytes",
		typeArray: "CodecArray", typeSlice: "CodecSlice", typeMap: "CodecMap", typeStruct: "CodecStruct",
	}[value.Kind]
	if value.Kind == typeStruct {
		var b strings.Builder
		fmt.Fprintf(&b, "configstore.ValueCodec{Kind: configstore.%s, Fields: []configstore.FieldCodec{", kind)
		for _, field := range value.Fields {
			if !field.Included {
				continue
			}
			fmt.Fprintf(&b, "{JSONName: %s, FieldIndex: []int{%d}, Value: %s},", strconv.Quote(field.JSONName), field.Index, r.codecLiteral(field.Type, indent+"\t"))
		}
		b.WriteString("}}")
		return b.String()
	}
	if value.Kind == typePointer || value.Kind == typeArray || value.Kind == typeSlice || value.Kind == typeMap {
		return fmt.Sprintf("configstore.ValueCodec{Kind: configstore.%s, Element: &%s}", kind, r.codecLiteral(value.Elem, indent+"\t"))
	}
	if value.Kind == typeInt || value.Kind == typeUint || value.Kind == typeFloat {
		return fmt.Sprintf("configstore.ValueCodec{Kind: configstore.%s, Bits: %d}", kind, value.Bits)
	}
	return fmt.Sprintf("configstore.ValueCodec{Kind: configstore.%s}", kind)
}

func (r *bindingRenderer) renderSnapshots() {
	r.line("// Current performs exactly one atomic load and captures that generation.")
	r.line("func (s *Store) Current() Snapshot {")
	r.line("\tgeneration := s.active.Load()")
	r.line("\treturn Snapshot{generation: generation}")
	r.line("}")
	r.line("")
	r.line("func (s Snapshot) Release() configstore.ReleaseIdentity { return s.generation.release }")
	r.line("")
	for _, view := range r.model.Views {
		r.line("func (s Snapshot) %s() %sView { return %sView{generation: s.generation} }", view.Method, view.Method, view.Method)
	}
	r.line("")
	for _, view := range r.model.Views {
		for _, field := range view.Fields {
			if field.Secret {
				r.line("func (v %sView) %s() paramstore.Secret { return v.generation.config.%s.Clone() }", view.Method, field.GoName, field.GoName)
				continue
			}
			if field.Type.Kind == typePointer {
				returnType := r.typeString(field.Type.Elem.GoType)
				r.line("func (v %sView) %s() %s {", view.Method, field.GoName, returnType)
				r.line("\tif v.generation.config.%s == nil {", field.GoName)
				r.line("\t\tvar zero %s", returnType)
				r.line("\t\treturn zero")
				r.line("\t}")
				r.line("\treturn *v.generation.config.%s", field.GoName)
				r.line("}")
				continue
			}
			returnType := r.typeString(field.Type.GoType)
			if field.Type.Mutable {
				h := r.helperByType[field.Type.GoType]
				r.line("func (v %sView) %s() %s { return cloneValue%d(v.generation.config.%s) }", view.Method, field.GoName, returnType, h, field.GoName)
			} else {
				r.line("func (v %sView) %s() %s { return v.generation.config.%s }", view.Method, field.GoName, returnType, field.GoName)
			}
		}
		r.line("")
	}
}

func (r *bindingRenderer) renderCloneRoot() {
	r.line("func cloneRoot(value *%s) *%s {", r.rootTypeString, r.rootTypeString)
	r.line("\tif value == nil { return nil }")
	r.line("\t// Root cloning is preparation-only. It also isolates excluded fields that generated getters never expose.")
	r.line("\tout := configstore.Clone(*value)")
	for _, field := range r.model.Fields {
		if field.Secret {
			r.line("\tout.%s = value.%s.Clone()", field.GoName, field.GoName)
		}
	}
	r.line("\treturn &out")
	r.line("}")
	r.line("")
}

func (r *bindingRenderer) addHelper(value *typeIR) int {
	if index, ok := r.helperByType[value.GoType]; ok {
		return index
	}
	index := len(r.helpers)
	r.helperByType[value.GoType] = index
	r.helpers = append(r.helpers, value)
	switch value.Kind {
	case typePointer, typeArray, typeSlice, typeMap:
		r.addHelper(value.Elem)
	case typeStruct:
		for _, field := range value.Fields {
			r.addHelper(field.Type)
		}
	}
	return index
}

func (r *bindingRenderer) renderHelpers() {
	for index, value := range r.helpers {
		r.renderCloneHelper(index, value)
		r.renderEqualHelper(index, value)
		r.renderReportHelper(index, value)
	}
}

func (r *bindingRenderer) renderCloneHelper(index int, value *typeIR) {
	typeName := r.typeString(value.GoType)
	r.line("func cloneValue%d(value %s) %s {", index, typeName, typeName)
	switch value.Kind {
	case typeBool, typeString, typeInt, typeUint, typeFloat, typeDuration:
		r.line("\treturn value")
	case typePointer:
		r.line("\tif value == nil { return nil }")
		elem := r.helperByType[value.Elem.GoType]
		r.line("\tcloned := cloneValue%d(*value)", elem)
		r.line("\treturn (%s)(&cloned)", typeName)
	case typeBytes:
		r.line("\tif value == nil { return nil }")
		r.line("\tout := make(%s, len(value))", typeName)
		r.line("\tcopy(out, value)")
		r.line("\treturn out")
	case typeSlice:
		elem := r.helperByType[value.Elem.GoType]
		r.line("\tif value == nil { return nil }")
		r.line("\tout := make(%s, len(value))", typeName)
		r.line("\tfor i := range value { out[i] = cloneValue%d(value[i]) }", elem)
		r.line("\treturn out")
	case typeArray:
		elem := r.helperByType[value.Elem.GoType]
		r.line("\tout := value")
		r.line("\tfor i := range value { out[i] = cloneValue%d(value[i]) }", elem)
		r.line("\treturn out")
	case typeMap:
		elem := r.helperByType[value.Elem.GoType]
		r.line("\tif value == nil { return nil }")
		r.line("\tout := make(%s, len(value))", typeName)
		r.line("\tfor key, item := range value { out[key] = cloneValue%d(item) }", elem)
		r.line("\treturn out")
	case typeStruct:
		r.line("\tout := value")
		for _, field := range value.Fields {
			if field.Type.Mutable {
				elem := r.helperByType[field.Type.GoType]
				r.line("\tout.%s = cloneValue%d(value.%s)", field.GoName, elem, field.GoName)
			}
		}
		r.line("\treturn out")
	}
	r.line("}")
	r.line("")
}

func (r *bindingRenderer) renderEqualHelper(index int, value *typeIR) {
	typeName := r.typeString(value.GoType)
	r.line("func equalValue%d(left, right %s) bool {", index, typeName)
	switch value.Kind {
	case typeBool, typeString, typeInt, typeUint, typeFloat, typeDuration:
		r.line("\treturn left == right")
	case typePointer:
		elem := r.helperByType[value.Elem.GoType]
		r.line("\tif left == nil || right == nil { return left == nil && right == nil }")
		r.line("\treturn equalValue%d(*left, *right)", elem)
	case typeBytes, typeSlice:
		elem := -1
		if value.Kind == typeSlice {
			elem = r.helperByType[value.Elem.GoType]
		}
		r.line("\tif (left == nil) != (right == nil) || len(left) != len(right) { return false }")
		r.line("\tfor i := range left {")
		if value.Kind == typeBytes {
			r.line("\t\tif left[i] != right[i] { return false }")
		} else {
			r.line("\t\tif !equalValue%d(left[i], right[i]) { return false }", elem)
		}
		r.line("\t}")
		r.line("\treturn true")
	case typeArray:
		elem := r.helperByType[value.Elem.GoType]
		r.line("\tfor i := range left { if !equalValue%d(left[i], right[i]) { return false } }", elem)
		r.line("\treturn true")
	case typeMap:
		elem := r.helperByType[value.Elem.GoType]
		r.line("\tif (left == nil) != (right == nil) || len(left) != len(right) { return false }")
		r.line("\tfor key, leftValue := range left {")
		r.line("\t\trightValue, ok := right[key]")
		r.line("\t\tif !ok || !equalValue%d(leftValue, rightValue) { return false }", elem)
		r.line("\t}")
		r.line("\treturn true")
	case typeStruct:
		if len(value.Fields) == 0 {
			r.line("\treturn true")
		} else {
			for _, field := range value.Fields {
				elem := r.helperByType[field.Type.GoType]
				r.line("\tif !equalValue%d(left.%s, right.%s) { return false }", elem, field.GoName, field.GoName)
			}
			r.line("\treturn true")
		}
	}
	r.line("}")
	r.line("")
}

func (r *bindingRenderer) renderReportHelper(index int, value *typeIR) {
	typeName := r.typeString(value.GoType)
	r.line("func reportValue%d(value %s) any {", index, typeName)
	if value.Kind == typePointer {
		r.line("\tif value == nil { return nil }")
		r.line("\treturn *value")
	} else if value.Mutable {
		r.line("\treturn cloneValue%d(value)", index)
	} else {
		r.line("\treturn value")
	}
	r.line("}")
	r.line("")
}
