package configgen

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"go/parser"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	_ "github.com/Suhaibinator/kms/internal/configgen/testdata/composedgenerated"
	_ "github.com/Suhaibinator/kms/internal/configgen/testdata/generated"
)

func TestGenerateIsDeterministicAndCanonical(t *testing.T) {
	options := validOptions(t)
	first, err := Generate(context.Background(), options)
	if err != nil {
		t.Fatal(err)
	}
	second, err := Generate(context.Background(), options)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(first.Binding, second.Binding) || !bytes.Equal(first.Schema, second.Schema) || !bytes.Equal(first.Contract, second.Contract) {
		t.Fatal("successive generations differ")
	}
	for name, data := range map[string][]byte{"binding": first.Binding, "schema": first.Schema, "contract": first.Contract} {
		if len(data) == 0 || data[len(data)-1] != '\n' {
			t.Errorf("%s is not newline terminated", name)
		}
	}
	if !bytes.HasPrefix(first.Binding, []byte("// Code generated by kms-config-gen; DO NOT EDIT.\n")) {
		t.Fatal("binding is missing generated header")
	}
	if _, err := parser.ParseFile(token.NewFileSet(), "binding.go", first.Binding, parser.AllErrors); err != nil {
		t.Fatalf("generated binding is not valid Go: %v", err)
	}
	if count := bytes.Count(first.Binding, []byte("s.active.Load()")); count != 2 {
		// Current has one load and preparation has one load for restart policy.
		t.Fatalf("active.Load count = %d, want 2", count)
	}
	if !bytes.Contains(first.Binding, []byte("func (s *Store) Current() Snapshot {\n\tgeneration := s.active.Load()")) {
		t.Fatal("Current does not contain the required single-load capture")
	}
	if bytes.Contains(first.Binding, []byte("reflect.")) {
		t.Fatal("generated binding unexpectedly uses reflection")
	}
	// Observers are supplied through the embedded configstore.Callbacks and
	// forwarded as one value; the removed startup bypass must not resurface.
	if !bytes.Contains(first.Binding, []byte("\tconfigstore.Callbacks\n")) ||
		!regexp.MustCompile(`Callbacks:\s+options\.Callbacks,`).Match(first.Binding) {
		t.Fatal("generated Options does not embed and forward configstore.Callbacks")
	}
	if bytes.Contains(first.Binding, []byte("AllowDefaultMismatch")) {
		t.Fatal("generated binding still references the removed AllowDefaultMismatch option")
	}
	if !bytes.Contains(first.Binding, []byte(`configstore.RejectDecode("database", err)`)) {
		t.Fatal("generated binding does not forward safe candidate rejection diagnostics")
	}
	// Reload change lists compare against the previously applied generation,
	// never against source defaults, and every candidate exposes its groups.
	changeAgainstActive := regexp.MustCompile(`configstore\.FieldChange\{Path: "database\.timeout", Previous: reportValue\d+\(active\.config\.Timeout\), Current: reportValue\d+\(candidate\.Timeout\)\}`)
	changeAgainstDefaults := regexp.MustCompile(`configstore\.FieldChange\{Path: "[^"]+", Previous: reportValue\d+\(effectiveDefaults\.`)
	if !changeAgainstActive.Match(first.Binding) || changeAgainstDefaults.Match(first.Binding) {
		t.Fatal("generated change list is not computed against the previously applied generation")
	}
	if !bytes.Contains(first.Binding, []byte(`configstore.FieldChange{Path: "database_password"}`)) {
		t.Fatal("generated change list does not report secret rotation path-only")
	}
	if !regexp.MustCompile(`Groups:\s+func\(\) \(map\[string\]json\.RawMessage, error\)`).Match(first.Binding) {
		t.Fatal("generated candidate does not set Groups")
	}
	if !bytes.Contains(first.Binding, []byte("func VerifyReleaseDefaults(")) {
		t.Fatal("generated binding does not emit VerifyReleaseDefaults")
	}
	for _, want := range [][]byte{
		[]byte("func EncodeDefaultsArtifact(profile string, root *rootconfig.Config) ([]byte, error)"),
		[]byte("Format:       configstore.DefaultsArtifactFormat"),
		[]byte("SchemaSHA256: generatedSchemaSHA256"),
		[]byte("Contract:     generatedContract"),
	} {
		if !bytes.Contains(first.Binding, want) {
			t.Fatalf("generated defaults encoder is missing %q", want)
		}
	}

	var schema map[string]any
	if err := json.Unmarshal(first.Schema, &schema); err != nil {
		t.Fatal(err)
	}
	if schema["$schema"] != "https://json-schema.org/draft/2020-12/schema" || schema["additionalProperties"] != false {
		t.Fatalf("unexpected schema header: %#v", schema)
	}
	properties := schema["properties"].(map[string]any)
	database := properties["database"].(map[string]any)
	databaseFields := database["properties"].(map[string]any)
	if databaseFields["timeout"].(map[string]any)["format"] != "go-duration" {
		t.Fatal("duration schema format missing")
	}
	rateLimits := properties["rate_limits"].(map[string]any)["properties"].(map[string]any)
	payloadSchema := nullableSchemaBranch(t, rateLimits["payload"], "string")
	if payloadSchema["format"] != "kms-base64" {
		t.Fatal("byte schema format missing")
	}
	if _, ok := properties["database_password"]; ok {
		t.Fatal("secret leaked into schema")
	}
	nullableSchemaBranch(t, rateLimits["ratio"], "number")
	endpointFields := databaseFields["endpoint"].(map[string]any)["properties"].(map[string]any)
	nullableSchemaBranch(t, endpointFields["ports"], "array")
	nullableSchemaBranch(t, endpointFields["labels"], "object")

	var contract struct {
		Format       string `json:"format"`
		SchemaSHA256 string `json:"schema_sha256"`
		Groups       []struct {
			Alias       string `json:"alias"`
			Kind        string `json:"kind"`
			ContentType string `json:"content_type"`
		} `json:"groups"`
		Secrets []struct {
			Alias string `json:"alias"`
			Kind  string `json:"kind"`
		} `json:"secrets"`
		Fields []struct {
			JSONName string `json:"json_name"`
			Encoding string `json:"encoding"`
		} `json:"fields"`
	}
	if err := json.Unmarshal(first.Contract, &contract); err != nil {
		t.Fatal(err)
	}
	var compactSchema bytes.Buffer
	if err := json.Compact(&compactSchema, first.Schema); err != nil {
		t.Fatal(err)
	}
	wantHash := sha256.Sum256(compactSchema.Bytes())
	if contract.Format != "kms-config-contract/v1" || contract.SchemaSHA256 != hex.EncodeToString(wantHash[:]) {
		t.Fatalf("unexpected contract identity: %#v", contract)
	}
	if len(contract.Groups) != 2 || contract.Groups[0].Alias != "database" || contract.Groups[0].Kind != "parameter" || contract.Groups[0].ContentType != "json" {
		t.Fatalf("unexpected contract groups: %#v", contract.Groups)
	}
	if len(contract.Secrets) != 1 || contract.Secrets[0].Alias != "database_password" || contract.Secrets[0].Kind != "secret" {
		t.Fatalf("unexpected contract secrets: %#v", contract.Secrets)
	}
	encodings := make(map[string]string, len(contract.Fields))
	for _, field := range contract.Fields {
		encodings[field.JSONName] = field.Encoding
	}
	if encodings["payload"] != "nullable-base64" || encodings["ratio"] != "nullable-float32" || encodings["endpoint"] != "object" {
		t.Fatalf("unexpected nullable contract encodings: %#v", encodings)
	}
	for _, forbidden := range []string{"default", "value", "physical_path", "token"} {
		if strings.Contains(strings.ToLower(string(first.Contract)), `"`+forbidden+`"`) {
			t.Fatalf("contract contains forbidden key %q", forbidden)
		}
	}
}

func TestTagAndTypeErrors(t *testing.T) {
	tests := []struct {
		typeName string
		want     string
	}{
		{"BothSources", "exactly one of group or secret"},
		{"UnknownClause", "unknown kms tag clause"},
		{"DuplicateClause", "duplicate kms tag clause"},
		{"MissingViews", "at least one kms_views"},
		{"DuplicateJSON", "JSON name"},
		{"Unsupported", "unsupported type"},
		{"Recursive", "recursive type"},
		{"Legacy", "legacy managed type"},
		{"BadSecret", `json:"-"`},
		{"BadValidate", "Validate method must have signature"},
		{"ViewCollision", "collides"},
		{"UnexportedRoot", "unexported root field"},
		{"ExcludedOpaque", "structurally deep-cloneable"},
		{"BadJSONName", "noncanonical JSON property name"},
		{"BadNestedJSONName", "noncanonical JSON property name"},
		{"InlineScalar", "must have an exported, non-generic named struct type"},
		{"InlineViews", "must not declare kms_views"},
		{"PromotedValidate", "must declare Validate() error directly"},
		{"EmptyInline", "contains no managed fields"},
		{"RecursiveInline", "recursive inline configuration"},
		{"DuplicateViewGetter", "getter Value is used by both"},
	}
	root := repoRoot(t)
	for _, test := range tests {
		t.Run(test.typeName, func(t *testing.T) {
			_, err := Generate(context.Background(), Options{
				Dir: root, Package: "./internal/configgen/testdata/invalid", Type: test.typeName, BindingPackage: "binding",
			})
			if err == nil || !strings.Contains(err.Error(), test.want) {
				t.Fatalf("error = %v, want substring %q", err, test.want)
			}
		})
	}
}

func TestGenerateComposesInlineFragments(t *testing.T) {
	root := repoRoot(t)
	artifacts, err := Generate(context.Background(), Options{
		Dir: root, Package: "./internal/configgen/testdata/composed", Type: "Config", BindingPackage: "composedgenerated",
	})
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		"FieldIndex: []int{0, 0}",
		"FieldIndex: []int{0, 2, 0}",
		"candidate.Common.Token = secret0.Clone()",
		"value.Common == nil",
		"value.Common.Limits == nil",
		"func (s Snapshot) Config() *rootconfig.Config",
	} {
		if !bytes.Contains(artifacts.Binding, []byte(want)) {
			t.Fatalf("generated binding is missing %q", want)
		}
	}

	var schema map[string]any
	if err := json.Unmarshal(artifacts.Schema, &schema); err != nil {
		t.Fatal(err)
	}
	properties := schema["properties"].(map[string]any)
	runtimeFields := properties["runtime"].(map[string]any)["properties"].(map[string]any)
	if _, ok := runtimeFields["burst"]; !ok {
		t.Fatal("inline common field burst is missing from the runtime group")
	}
	if _, ok := runtimeFields["app_name"]; !ok {
		t.Fatal("application field app_name is missing from the shared runtime group")
	}

	var contract struct {
		Source contractSource `json:"source"`
		Fields []struct {
			JSONName string `json:"json_name"`
			GoName   string `json:"go_name"`
			GoPath   string `json:"go_path"`
		} `json:"fields"`
		Secrets []struct {
			Alias  string `json:"alias"`
			GoName string `json:"go_name"`
			GoPath string `json:"go_path"`
		} `json:"secrets"`
	}
	if err := json.Unmarshal(artifacts.Contract, &contract); err != nil {
		t.Fatal(err)
	}
	if contract.Source.Package != "github.com/Suhaibinator/kms/internal/configgen/testdata/composed" || contract.Source.Type != "Config" {
		t.Fatalf("contract source = %#v", contract.Source)
	}
	fieldPaths := make(map[string]string, len(contract.Fields))
	for _, field := range contract.Fields {
		fieldPaths[field.JSONName] = field.GoPath
		if field.GoName == "" {
			t.Fatalf("contract field %q lost backward-compatible go_name", field.JSONName)
		}
	}
	if fieldPaths["endpoint"] != "Common.Endpoint" || fieldPaths["burst"] != "Common.Limits.Burst" || fieldPaths["app_name"] != "AppName" {
		t.Fatalf("contract field go paths = %#v", fieldPaths)
	}
	if len(contract.Secrets) != 1 || contract.Secrets[0].Alias != "common_token" || contract.Secrets[0].GoName != "Token" || contract.Secrets[0].GoPath != "Common.Token" {
		t.Fatalf("contract secrets = %#v", contract.Secrets)
	}

	if _, err := Generate(context.Background(), Options{
		Dir: root, Package: "./internal/configgen/testdata/composed", Type: "EmbeddedConfig", BindingPackage: "embeddedgenerated",
	}); err != nil {
		t.Fatalf("anonymous inline fragment: %v", err)
	}
}

func nullableSchemaBranch(t *testing.T, value any, wantType string) map[string]any {
	t.Helper()
	schema, ok := value.(map[string]any)
	if !ok {
		t.Fatalf("schema = %#v, want object", value)
	}
	branches, ok := schema["anyOf"].([]any)
	if !ok || len(branches) != 2 {
		t.Fatalf("schema = %#v, want two anyOf branches", schema)
	}
	var typed map[string]any
	hasNull := false
	for _, raw := range branches {
		branch, ok := raw.(map[string]any)
		if !ok {
			continue
		}
		switch branch["type"] {
		case wantType:
			typed = branch
		case "null":
			hasNull = true
		}
	}
	if typed == nil || !hasNull {
		t.Fatalf("schema = %#v, want %s and null branches", schema, wantType)
	}
	return typed
}

func TestGenerateSecretOnlyRootHasValidEmptySchema(t *testing.T) {
	artifacts, err := Generate(context.Background(), Options{
		Dir: repoRoot(t), Package: "./internal/configgen/testdata/valid", Type: "SecretsOnly", BindingPackage: "binding",
	})
	if err != nil {
		t.Fatal(err)
	}
	var schema struct {
		Required   []string       `json:"required"`
		Properties map[string]any `json:"properties"`
	}
	if err := json.Unmarshal(artifacts.Schema, &schema); err != nil {
		t.Fatal(err)
	}
	if schema.Required == nil || len(schema.Required) != 0 || schema.Properties == nil || len(schema.Properties) != 0 {
		t.Fatalf("secret-only schema = required:%#v properties:%#v", schema.Required, schema.Properties)
	}
	if _, err := parser.ParseFile(token.NewFileSet(), "secret_only.gen.go", artifacts.Binding, parser.AllErrors); err != nil {
		t.Fatalf("secret-only binding is invalid Go: %v", err)
	}
}

func TestGeneratedDefaultComparisonUsesValidatedDefaults(t *testing.T) {
	root := repoRoot(t)
	artifacts, err := Generate(context.Background(), Options{
		Dir: root, Package: "./internal/configgen/testdata/mutating", Type: "Config", BindingPackage: "mutatinggenerated",
	})
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(artifacts.Binding, []byte("if !equalValue0(effectiveDefaults.Name, candidate.Name)")) {
		t.Fatal("generated default drift comparison bypasses the validated effective defaults")
	}
	if bytes.Contains(artifacts.Binding, []byte("if !equalValue0(s.defaults.Name, candidate.Name)")) {
		t.Fatal("generated default drift comparison uses the original unvalidated defaults")
	}
	if !bytes.Contains(artifacts.Binding, []byte("effectiveDefaults.Token = secret0.Clone()")) {
		t.Fatal("effective defaults do not receive an independent clone of the raw resolved secret")
	}
	if bytes.Contains(artifacts.Binding, []byte("effectiveDefaults.Token = candidate.Token.Clone()")) {
		t.Fatal("effective defaults receive secret bytes after candidate validation may have mutated them")
	}
	err = Verify(OutputPaths{
		Binding:  filepath.Join(root, "internal/configgen/testdata/mutatinggenerated/config.gen.go"),
		Schema:   filepath.Join(root, "internal/configgen/testdata/mutatinggenerated/runtime.schema.json"),
		Contract: filepath.Join(root, "internal/configgen/testdata/mutatinggenerated/runtime.contract.json"),
	}, artifacts)
	if err != nil {
		t.Fatal(err)
	}
}

func TestGenerateRejectsProgramRootPackage(t *testing.T) {
	_, err := Generate(context.Background(), Options{
		Dir: repoRoot(t), Package: "./internal/configgen/testdata/mainconfig", Type: "Config", BindingPackage: "binding",
	})
	if err == nil || !strings.Contains(err.Error(), "program") {
		t.Fatalf("program root error = %v", err)
	}
}

func TestMachineSizedIntegerContractIsArchitectureIndependent(t *testing.T) {
	for _, arch := range []string{"386", "amd64"} {
		value, err := analyzeType(types.Typ[types.Int], types.SizesFor("gc", arch), make(map[types.Type]bool), "test int")
		if err != nil {
			t.Fatal(err)
		}
		if value.Bits != 32 || canonicalEncoding(value) != "int32" {
			t.Fatalf("%s int contract = bits:%d encoding:%s", arch, value.Bits, canonicalEncoding(value))
		}
	}
}

func TestWriteAndVerify(t *testing.T) {
	artifacts, err := Generate(context.Background(), validOptions(t))
	if err != nil {
		t.Fatal(err)
	}
	dir := t.TempDir()
	paths := OutputPaths{
		Binding:  filepath.Join(dir, "binding", "config.gen.go"),
		Schema:   filepath.Join(dir, "runtime.schema.json"),
		Contract: filepath.Join(dir, "runtime.contract.json"),
	}
	if err := Write(paths, artifacts); err != nil {
		t.Fatal(err)
	}
	if err := Verify(paths, artifacts); err != nil {
		t.Fatal(err)
	}
	before, err := os.Stat(paths.Schema)
	if err != nil {
		t.Fatal(err)
	}
	if err := Write(paths, artifacts); err != nil {
		t.Fatal(err)
	}
	after, err := os.Stat(paths.Schema)
	if err != nil {
		t.Fatal(err)
	}
	if !before.ModTime().Equal(after.ModTime()) {
		t.Fatal("matching output was needlessly rewritten")
	}
	if err := os.WriteFile(paths.Schema, []byte("stale\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	err = Verify(paths, artifacts)
	if !errors.Is(err, ErrStale) {
		t.Fatalf("Verify error = %v, want ErrStale", err)
	}
	contents, readErr := os.ReadFile(paths.Schema)
	if readErr != nil || string(contents) != "stale\n" {
		t.Fatalf("Verify changed stale output: %q, %v", contents, readErr)
	}
}

func TestCommittedCompileFixtureIsFresh(t *testing.T) {
	root := repoRoot(t)
	artifacts, err := Generate(context.Background(), Options{
		Dir: root, Package: "./internal/configgen/testdata/valid", Type: "Config", BindingPackage: "generated",
	})
	if err != nil {
		t.Fatal(err)
	}
	err = Verify(OutputPaths{
		Binding:  filepath.Join(root, "internal/configgen/testdata/generated/config.gen.go"),
		Schema:   filepath.Join(root, "internal/configgen/testdata/generated/runtime.schema.json"),
		Contract: filepath.Join(root, "internal/configgen/testdata/generated/runtime.contract.json"),
	}, artifacts)
	if err != nil {
		t.Fatal(err)
	}
}

func TestCommittedComposedCompileFixtureIsFresh(t *testing.T) {
	root := repoRoot(t)
	artifacts, err := Generate(context.Background(), Options{
		Dir: root, Package: "./internal/configgen/testdata/composed", Type: "Config", BindingPackage: "composedgenerated",
	})
	if err != nil {
		t.Fatal(err)
	}
	if err := Verify(OutputPaths{
		Binding:  filepath.Join(root, "internal/configgen/testdata/composedgenerated/config.gen.go"),
		Schema:   filepath.Join(root, "internal/configgen/testdata/composedgenerated/runtime.schema.json"),
		Contract: filepath.Join(root, "internal/configgen/testdata/composedgenerated/runtime.contract.json"),
	}, artifacts); err != nil {
		t.Fatal(err)
	}
}

func validOptions(t *testing.T) Options {
	t.Helper()
	return Options{Dir: repoRoot(t), Package: "./internal/configgen/testdata/valid", Type: "Config", BindingPackage: "configkms"}
}

func repoRoot(t *testing.T) string {
	t.Helper()
	root, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatal(err)
	}
	return root
}
