package configgen

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"testing"

	_ "github.com/Suhaibinator/kms/internal/configgen/testdata/generated"
)

func TestGenerateIsDeterministicAndCanonical(t *testing.T) {
	options := validOptions(t)
	first, err := Generate(context.Background(), options)
	if err != nil {
		t.Fatal(err)
	}
	second, err := Generate(context.Background(), options)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(first.Binding, second.Binding) || !bytes.Equal(first.Schema, second.Schema) || !bytes.Equal(first.Contract, second.Contract) {
		t.Fatal("successive generations differ")
	}
	for name, data := range map[string][]byte{"binding": first.Binding, "schema": first.Schema, "contract": first.Contract} {
		if len(data) == 0 || data[len(data)-1] != '\n' {
			t.Errorf("%s is not newline terminated", name)
		}
	}
	if !bytes.HasPrefix(first.Binding, []byte("// Code generated by kms-config-gen; DO NOT EDIT.\n")) {
		t.Fatal("binding is missing generated header")
	}
	if _, err := parser.ParseFile(token.NewFileSet(), "binding.go", first.Binding, parser.AllErrors); err != nil {
		t.Fatalf("generated binding is not valid Go: %v", err)
	}
	if count := bytes.Count(first.Binding, []byte("s.active.Load()")); count != 2 {
		// Current has one load and preparation has one load for restart policy.
		t.Fatalf("active.Load count = %d, want 2", count)
	}
	if !bytes.Contains(first.Binding, []byte("func (s *Store) Current() Snapshot {\n\tgeneration := s.active.Load()")) {
		t.Fatal("Current does not contain the required single-load capture")
	}
	if bytes.Contains(first.Binding, []byte("reflect.")) {
		t.Fatal("generated binding unexpectedly uses reflection")
	}

	var schema map[string]any
	if err := json.Unmarshal(first.Schema, &schema); err != nil {
		t.Fatal(err)
	}
	if schema["$schema"] != "https://json-schema.org/draft/2020-12/schema" || schema["additionalProperties"] != false {
		t.Fatalf("unexpected schema header: %#v", schema)
	}
	properties := schema["properties"].(map[string]any)
	database := properties["database"].(map[string]any)
	databaseFields := database["properties"].(map[string]any)
	if databaseFields["timeout"].(map[string]any)["format"] != "go-duration" {
		t.Fatal("duration schema format missing")
	}
	rateLimits := properties["rate_limits"].(map[string]any)["properties"].(map[string]any)
	if rateLimits["payload"].(map[string]any)["format"] != "kms-base64" {
		t.Fatal("byte schema format missing")
	}
	if _, ok := properties["database_password"]; ok {
		t.Fatal("secret leaked into schema")
	}
	if _, ok := rateLimits["ratio"].(map[string]any)["anyOf"]; !ok {
		t.Fatal("pointer-to-scalar schema is not nullable")
	}

	var contract struct {
		Format       string `json:"format"`
		SchemaSHA256 string `json:"schema_sha256"`
		Groups       []struct {
			Alias       string `json:"alias"`
			Kind        string `json:"kind"`
			ContentType string `json:"content_type"`
		} `json:"groups"`
		Secrets []struct {
			Alias string `json:"alias"`
			Kind  string `json:"kind"`
		} `json:"secrets"`
	}
	if err := json.Unmarshal(first.Contract, &contract); err != nil {
		t.Fatal(err)
	}
	wantHash := sha256.Sum256(first.Schema)
	if contract.Format != "kms-config-contract/v1" || contract.SchemaSHA256 != hex.EncodeToString(wantHash[:]) {
		t.Fatalf("unexpected contract identity: %#v", contract)
	}
	if len(contract.Groups) != 2 || contract.Groups[0].Alias != "database" || contract.Groups[0].Kind != "parameter" || contract.Groups[0].ContentType != "json" {
		t.Fatalf("unexpected contract groups: %#v", contract.Groups)
	}
	if len(contract.Secrets) != 1 || contract.Secrets[0].Alias != "database_password" || contract.Secrets[0].Kind != "secret" {
		t.Fatalf("unexpected contract secrets: %#v", contract.Secrets)
	}
	for _, forbidden := range []string{"default", "value", "physical_path", "token"} {
		if strings.Contains(strings.ToLower(string(first.Contract)), `"`+forbidden+`"`) {
			t.Fatalf("contract contains forbidden key %q", forbidden)
		}
	}
}

func TestTagAndTypeErrors(t *testing.T) {
	tests := []struct {
		typeName string
		want     string
	}{
		{"BothSources", "exactly one of group or secret"},
		{"UnknownClause", "unknown kms tag clause"},
		{"DuplicateClause", "duplicate kms tag clause"},
		{"MissingViews", "at least one kms_views"},
		{"DuplicateJSON", "JSON name"},
		{"Unsupported", "unsupported type"},
		{"Recursive", "recursive type"},
		{"Legacy", "legacy managed type"},
		{"BadSecret", `json:"-"`},
		{"BadValidate", "Validate method must have signature"},
		{"ViewCollision", "collides"},
	}
	root := repoRoot(t)
	for _, test := range tests {
		t.Run(test.typeName, func(t *testing.T) {
			_, err := Generate(context.Background(), Options{
				Dir: root, Package: "./internal/configgen/testdata/invalid", Type: test.typeName, BindingPackage: "binding",
			})
			if err == nil || !strings.Contains(err.Error(), test.want) {
				t.Fatalf("error = %v, want substring %q", err, test.want)
			}
		})
	}
}

func TestWriteAndVerify(t *testing.T) {
	artifacts, err := Generate(context.Background(), validOptions(t))
	if err != nil {
		t.Fatal(err)
	}
	dir := t.TempDir()
	paths := OutputPaths{
		Binding:  filepath.Join(dir, "binding", "config.gen.go"),
		Schema:   filepath.Join(dir, "runtime.schema.json"),
		Contract: filepath.Join(dir, "runtime.contract.json"),
	}
	if err := Write(paths, artifacts); err != nil {
		t.Fatal(err)
	}
	if err := Verify(paths, artifacts); err != nil {
		t.Fatal(err)
	}
	before, err := os.Stat(paths.Schema)
	if err != nil {
		t.Fatal(err)
	}
	if err := Write(paths, artifacts); err != nil {
		t.Fatal(err)
	}
	after, err := os.Stat(paths.Schema)
	if err != nil {
		t.Fatal(err)
	}
	if !before.ModTime().Equal(after.ModTime()) {
		t.Fatal("matching output was needlessly rewritten")
	}
	if err := os.WriteFile(paths.Schema, []byte("stale\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	err = Verify(paths, artifacts)
	if !errors.Is(err, ErrStale) {
		t.Fatalf("Verify error = %v, want ErrStale", err)
	}
	contents, readErr := os.ReadFile(paths.Schema)
	if readErr != nil || string(contents) != "stale\n" {
		t.Fatalf("Verify changed stale output: %q, %v", contents, readErr)
	}
}

func TestCommittedCompileFixtureIsFresh(t *testing.T) {
	root := repoRoot(t)
	artifacts, err := Generate(context.Background(), Options{
		Dir: root, Package: "./internal/configgen/testdata/valid", Type: "Config", BindingPackage: "generated",
	})
	if err != nil {
		t.Fatal(err)
	}
	err = Verify(OutputPaths{
		Binding:  filepath.Join(root, "internal/configgen/testdata/generated/config.gen.go"),
		Schema:   filepath.Join(root, "internal/configgen/testdata/generated/runtime.schema.json"),
		Contract: filepath.Join(root, "internal/configgen/testdata/generated/runtime.contract.json"),
	}, artifacts)
	if err != nil {
		t.Fatal(err)
	}
}

func validOptions(t *testing.T) Options {
	t.Helper()
	return Options{Dir: repoRoot(t), Package: "./internal/configgen/testdata/valid", Type: "Config", BindingPackage: "configkms"}
}

func repoRoot(t *testing.T) string {
	t.Helper()
	root, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatal(err)
	}
	return root
}
